#include "CLLanguage_IT.h"

const char* gLanguage_ITTexts[ CLTextId__TEXT_COUNT ] =
{
	"BYPASS",   /* BYPASS */
	"DEFROST",   /* DEFROST */
	"FILTRI",   /* FILTERS */
	"MENU",   /* MENU */
	"SALVA",   /* SAVE */
	"ORA",   /* TIME */
	"DATA",   /* DATE */
	"TIPO KTS",   /* SELECT_KTS */
	"CONFIG. BOX INFO",   /* CONFIG_BOX_INFO */
	"SELEZIONA LINGUA",   /* SELECTION_LANGUAGE */
	"SETTAG. SCREENSAVER",   /* CONFIG_SCREEN_SAVER */
	"AGGIORNAMENTO",   /* UPGRADE */
	"SETTAGGIO DATA",   /* DATE_SETTINGS */
	"IMPOST. 3 VELOCITA'",   /* THREE_SPEED_SETTINGS */
	"PROGRAMMATORE SETT.",   /* WEEKLY_PROGRAMMER */
	"CALIBRAZIONE TOUCH",   /* TOUCH_CALIBRATION */
	"SETTAGGIO FILTRI",   /* FILTER_SETTINGS */
	"SETTAGGIO BPD",   /* BPD_SETTINGS */
	"SBILANCIO PORTATA",   /* UNBALANCE_AIRFLOW */
	"ATTIV. AGGIORNAMENTO",   /* UPGRADE_ACTIVATION */
	"PASSWORD NON VALIDA",   /* PASSWORD_INCORRECT */
	"SERIALE ID",   /* SERIAL_ID */
	"VERSIONE FIRMWARE",   /* FIRMWARE_VERSION */
	"TIPO UNITA'",   /* UNIT_TYPE */
	"ACCESSORI",   /* ACCESSORY */
	"SETTAGGI",   /* SETTINGS */
	"MANUTENZIONE",   /* SERVICE */
	"INFO",   /* INFO */
	"SELEZIONA LINGUA",   /* SELECT_LANGUAGE */
	"L",   /* MONDAY_SHORTNAME */
	"M",   /* TUESDAY_SHORTNAME */
	"M",   /* WEBNESDAY_SHORTNAME */
	"G",   /* THURSDAY_SHORTNAME */
	"V",   /* FRIDAY_SHORTNAME */
	"S",   /* SATURDAY_SHORTNAME */
	"D",   /* SUNDAY_SHORTNAME */
	"INCOL",   /* PASTE */
	"COPI",   /* COPY */
	"IMPOSTA FASCIA 1",   /* SET_FIRST_RANGE */
	"IMPOSTA FASCIA 2",   /* SET_SECOND_RANGE */
	"IMPOSTA FASCIA 3",   /* SET_THIRD_RANGE */
	"IMPOSTA FASCIA 4",   /* SET_FOURTH_RANGE */
	"INIZIO",   /* START_TIME */
	"FINE",   /* END_TIME */
	"PORTATA",   /* AIR_FLOW */
	"LUNEDI",   /* MONDAY */
	"MARTEDI",   /* TUESDAY */
	"MERCOLEDI",   /* WEDNESDAY */
	"GIOVEDI",   /* THURSDAY */
	"VENERDI",   /* FRIDAY */
	"SABATO",   /* SATURDAY */
	"DOMENICA",   /* SUNDAY */
	"USARE UNO STILO",   /* MAKE_USE_OF_A_STYLUS_PEN */
	"PREMERE LA BARRA BLU",   /* PRESS_THE_BLUE_BAR */
	"SELEZIONA MOD.VEL.",   /* SELECT_SPEED_MODE */
	"3 VELOCITA",   /* THREE_SPEED */
	"REG.CONTINUA",   /* STEPLESS */
	"IMPOSTA VEL MIN",   /* SELECT_SPEED_MIN */
	"IMPOSTA VEL MED",   /* SELECT_SPEED_MED */
	"IMPOSTA VEL MAX",   /* SELECT_SPEED_MAX */
	"IMPOSTA TEMPO FILTRI",   /* SET_FILTER_TIME */
	"MESI",   /* MONTHS */
	"IMPOSTA SBILANC.",   /* SET_UNBALANCE */
	"IND.",   /* BACK */
	"GESTIONE ACCESSORI",   /* ACCESSORY_MANAGER */
	"GESTIONE CLIMA",   /* CLIMA_SETTINGS */
	"IMPOSTAZIONI TEMP.",   /* TEMPERATURE_SETTINGS */
	"IMPOSTAZIONI SETT.",   /* WEEKLY_SETTINGS */
	"PROGRAMMA",   /* PROGRAM */
	"VISUALIZZA",   /* VIEW */
	"PROG",   /* PROG */
	"NUM.INTERVALLI",   /* SET_NBR_OF_RANGES */
	"RIPRESA",   /* RETURN */
	"UNITA'",   /* UNIT */
	"RICERCA...",   /* SEARCHING */
	"ERRORE",   /* ERROR */
	"UNITA' NON TROVATA",   /* UNIT_NOT_FOUND */
	"CONTROLLARE IL",   /* PLEASE_CHECK_THE */
	"CAVO E RIAVVIARE",   /* CABLE_AND_RESTART */
	"IL SISTEMA",   /* THE_SYSTEM */
	"CONNESSA",   /* CONNECTED */
	"DISAB.",   /* DISABLE */
	"TOUCH CALIBRATO",   /* TOUCH_CALIBRATED */
	"LISTA DEGLI ERRORI",   /* WARNINGS_REPORT */
	"CAMBIARE FILTRI",   /* RECOMMEND_TO_CHANGE_FILTERS */
	"PASSWORD CORRETTA",   /* PASSWORD_CORRECT */
	"DOM",   /* SUN */
	"LUN",   /* MON */
	"MAR",   /* TUE */
	"MER",   /* WED */
	"GIO",   /* THU */
	"VEN",   /* FRI */
	"SAB",   /* SAT */
	"NC",   /* NC */
	"IMPOSTAZIONI RH",   /* RH_SETTINGS */
	"IMPOSTA SOGLIA RH",   /* SET_RH_THRESHOLD */
	"IMPOSTAZIONI CO2",   /* CO2_SETTINGS */
	"    CO2     PORTATA",   /* SET_CO2_THRESHOLD */
	"CONTA ORE",   /* COUNTER */
	"SETTAGGIO PARTY",   /* PARTY_SETTINGS */
	"SETTA PARTY TIMER:",   /* SET_PARTY_TIMER */
	"EVENTO",   /* EVENT */
	"SETT.",   /* WEEK */
	"SONDE",   /* PROBES */
	"CONFIG",   /* CONFIG */
	"SET. ISTERESI",   /* HYSTER_TEMPSET */
	"ESTATE",   /* SUMMER */
	"INVERNO",   /* WINTER */
	"T.RINNOV.",   /* TFRESH */
	"ISTERESI TEMPER.",   /* TEMPERATURE_HYSTERESIS */
	"IMMISSIONE",   /* SUPPLY */
	"ESTRAZIONE",   /* EXTRACT */
	"REPORT DATI",   /* REPORT_DATA */
	"SENSORE PRESSIONE:",   /* PRESSURE_SENSOR */
	"LIVELLO SEGNALE:",   /* LEVEL_LINK_SENSOR */
	"PRESSIONE IMPOSTAT:",   /* SETPOINT_PRESSURE */
	"PRESSIONE MISURATA:",   /* MEASURE_PRESSURE */
	"VELOCITA VENTOLE:",   /* SPEED_MOTORS */
	"CONNESSO",   /* CONNECT */
	"NON CONNES.",   /* NOT_CONNECTED */
	"RIMOZIONE ACCESSORIO",   /* REMOVE_ACCESSORY */
	"CONFERMI RIMOZIONE?",   /* CONFIRM_REMOVE */
	"T. RIPRESA",   /* TRETURN */
	"SI",   /* YES */
	"NO",   /* NO */
	"MANUALE",   /* MANUAL */
	"AUTOMATICO (ACCESO)",   /* AUTOMATIC_ON */
	"APERTO",   /* OPEN */
	"CHIUSO",   /* CLOSED */
	"CLIMA",   /* CLIMA */
	"PASSWORD",   /* PASSWORD */
	"HOT",   /* HOT */
	"COLD",   /* COLD */
	"RESET",   /* RESET */
	"CONFIGURAZ. INPUT",   /* INPUT_CONFIG */
	"0V = STOP",   /* INPUT_CONFIG_0V_STOP */
	"10V = STOP",   /* INPUT_CONFIG_10V_STOP */
	"0V = OPEN",   /* INPUT_CONFIG_0V_OPEN */
	"10V = OPEN",   /* INPUT_CONFIG_10V_OPEN */
	"REG AIR FLOW",   /* INPUT_CONFIG_REG_AIR_FLOW */
	"CONFIGURAZ. OUTPUT",   /* OUTPUT_CONFIG */
	"SELEZIONE CLASSE TX",   /* SELECT_FRANCE_CLASSTX */
	"CLASSE TX",   /* FRANCE_CLASSTX */
	"CONTROLLO VENTILAZIONE",   /* VENTILATION_CONTROL */
	"CONFIGURAZ. VOC",   /* VOC_CONFIG */
	"TEMPERATURE",   /* TEMPERATURE */
	"VELOCITA'",   /* SPEED */
	"CONTROLLO CLIMA",   /* CLIMA_CONTROL */
	"SCRITTURA DATI IN CORSO...",   /* WRITING_DATA */
	"SCRITTURA DATI COMPLETATA",   /* WRITING_DATA_COMPLETED */
	"ERRORE DURANTE LA SCRITTURA DEI DATI",   /* WRITING_DATA_ERROR */
	"IN ALLARME",   /* IN_ALARM */
	"CONTROLLO ESTERNO",   /* EXTERNAL_CONTROL */
	"LISTA DEGLI ERRORI",   /* ERRORS_REPORT */
	"IMP. RANGE",   /* SET_RANGE */
	"MAN. OFF",   /* MANUAL_OFF */
	"MAN. ON",   /* MANUAL_ON */
	"MAN. CHIUSO",   /* MANUAL_CLOSE */
	"MAN. APERTO",   /* MANUAL_OPEN */
	"AUT. OFF",   /* AUT_OFF */
	"AUT. ON",   /* AUT_ON */
	"CHANGING",   /* CHANGING */
	"MIN.",   /* MINUTE_ABBR */
	"CONFIGURAZ. AIR FLOW",   /* AIRFLOW_CONFIG */
	"ACQUA CK",   /* WATER_CK */
	"SELEZIONE EVENTO",   /* SELECT_EVENT */
	"BYPASS APERTO",   /* BYPASS_OPEN */
	"BYPASS CHIUSO",   /* BYPASS_CLOSE */
	"UNIT RUN",   /* UNIT_RUN */
	"UNIT FAULT",   /* UNIT_FAULT */
	"SELEZIONE AZIONE",   /* SELECT_ACTION */
	"VECCHIA PASSWORD",   /* OLD_PASSWORD */
	"NUOVA PASSWORD",   /* NEW_PASSWORD */
	"RIPETI NUOVA PASSWORD",   /* REPEAT_NEW_PASSWORD */
	"CAMBIA PWD UTENTE",   /* CHANGE_END_USER_PASSWORD */
	"CAMBIA PWD SERVICE",   /* CHANGE_SERVICE_PASSWORD */
	"CAMBIA PASSWORD",   /* CHANGE_PASSWORD */
	"IMPOSTAZ. PWD",   /* PASSWORD_SETTINGS */
	"DATI MODIFICATI",   /* DATA_CHANGED */
	"SALVARE LE MODIFICHE?",   /* SAVE_CHANGES */
	"ANNULLA",   /* CANCEL */
	"IMPOSTAZ. SONDE",   /* PROBES_SETTINGS */
	"RISCALDAMENTO",   /* HEATER */
	"RAFFREDDAMENTO",   /* COOLER */
	"GIORNI",   /* DAYS */
	"DISCONN. ACC.",   /* DISCONNECT_ACCESSORY */
	"ACC. CLIMA",   /* BOXINFO_ACCESSORY_CLIMA */
	"VERSIONE MB HARDWARE",   /* MB_HARDWARE_VERSION */
	"VERSIONE MB SOFTWARE",   /* MB_SOFTWARE_VERSION */
	"PRE RISCALD.",   /* PREHEATER */
	"POST RISCALD.",   /* POSTHEATER */
	CLText_NoText,   /* INTERNAL */
	"PORTATA",   /* MEASURE_AIRFLOW */
	"IMPOSTAZIONI MODBUS ",   /* MODBUS_SETTINGS */
	"INDIRIZZO",   /* MODBUS_ADDRESS */
	"STATO",   /* MODBUS_STATUS */
	"DISCONNESSO",   /* DISCONNECTED */
	"TEMP. MIN. ESTERNA",   /* BYPASS_MIN_EXT_TEMPERATURE */
	"MODBUS ABILITATO. DATI ACCESSIBILI DA MODBUS.",   /* DATA_AVAILABLE_FROM_MODBUS */
	"CANALE",   /* RFM__CHANNEL */
	"STATO",   /* RFM__STATUS */
	"CAMBIA CANALE RFM",   /* RFM__CHANGE_CHANNEL */
	"CONNESSIONE",   /* CONNECTING */
	"LIBERO",   /* RFM__CHANNEL_FREE */
	"OCCUPATO",   /* RFM__CHANNEL_BUSY */
	"IN CORSO",   /* RFM__CHANNEL_INPROGRESS */
	"CANALE RFM OCCUPATO. CAMBIARE CANALE.",   /* RFM__ALERT_CHANNEL_BUSY */
	"PREMI OK PER RIPROVARE LA CONNESSIONE",   /* CONNECT__RETRY_CONNECTION_MESSAGE */
	"CONTROLLO DEL CANALE RFM IN CORSO",   /* RFM__CHECKING_CHANNEL_IN_PROGRESS */
	"ALLARME FUOCO",   /* FIREALARM_FIRE_ALARM */
	"CONFIG. RIFERIMENTI T.",   /* REFERENCE_T_SETTING */
	"SEC.",   /* SECOND_ABBR */
	"SONDA DI RIFERIMENTO",   /* DXDSETTINGS_REFERENCEPROBE */
	"DELTA TEMPERATURA",   /* DXDSETTINGS_DELTATEMPERATURE */
	"RITARDO",   /* DXDSETTINGS_DELAY */
	"BYPASS GESTITO TRAMITE INPUT",   /* BYPASS_OPERATED_BY_EXT_INPUT */
	"PROCEDURA CALIBRAZIONE CAP",   /* CAP_CALIBRATION_PROCEDURE */
	"APRIRE TUTTE LE VALVOLE DELL'IMPIANTO E PREMERE OK PER INIZIARE",   /* CAP_CALIBRATION_START_MESSAGE */
	"CALIBRAZIONE IN CORSO\nATTENDERE PREGO...",   /* CAP_CALIBRATION_RUNNING_MESSAGE */
	"CONFERMI LA PRESSIONE RILEVATA?",   /* CAP_CALIBRATION_CONFIRMDATA_MESSAGE */
	"AUTOMATICO (ACCESO + STANDBY)",   /* AUTOMATIC_ON_STANDBY */
	"ALLARME FUOCO ATTIVO",   /* FIREALARM_ALARM_ACTIVATED */
	"ALLARME FUOCO NON ATTIVO",   /* FIREALARM_ALARM_DEACTIVATED */
	"CONFIGURAZIONE",   /* FIREALARM_CONFIGURATION */
	"PER RIATTIVARE IL NORMALE FUNZIONAMENTO DELLA MACCHINA OCCORRE PREMERE IL TASTO RIARMO",   /* FIREALARM_REARM_MESSAGE */
	"RIARMO",   /* FIREALARM_REARM */
	CLText_NoText,
	"VUOI ESEGUIRE LA PROCEDURA?", /* PROCEDURE_STARTING_MESSAGE */
	"PROCEDURA IN ESECUZIONE...", /* PROCEDURE_RUNNING_MESSAGE */
	"PROCEDURA COMPLETATA", /* PROCEDURE_COMPLETED_MESSAGE */
	"SOGLIA", /* DPP_THRESHOLD */
	"CALIBRAZIONE", /* DPP_CALIBRATION */
	"LIVELLO FILTRO", /* DPP_FILTER_LEVEL */
	"DISCONNETTI TUTTI", /* Disconnect all accessories */
};

