#include "CLLanguage_DE.h"

const char* gLanguage_DETexts[ CLTextId__TEXT_COUNT ] =
{
	"BYPASS",   /* BYPASS */
	"DEFROST",   /* DEFROST */
	"FILTER",   /* FILTERS */
	"MENU",   /* MENU */
	"SPEI.",   /* SAVE */
	"ZEIT",   /* TIME */
	"DATUM",   /* DATE */
	"AUSWAHL TOUCH",   /* SELECT_KTS */
	"SET BOX INFO",   /* CONFIG_BOX_INFO */
	"SPRACHAUSWAHL",   /* SELECTION_LANGUAGE */
	"BILDSCHIRMSCHONER",   /* CONFIG_SCREEN_SAVER */
	"UPDATE",   /* UPGRADE */
	"DATUM EINSTELLUNG",   /* DATE_SETTINGS */
	"3 STUFEN BETRIEB",   /* THREE_SPEED_SETTINGS */
	"WOCHENPROGRAMM",   /* WEEKLY_PROGRAMMER */
	"TOUCH KALIBRIERUNG",   /* TOUCH_CALIBRATION */
	"FILTER EINSTELLUNGEN",   /* FILTER_SETTINGS */
	"BYPASS EINSTELLUNGEN",   /* BPD_SETTINGS */
	"VOLUMENSTROMUNGLEICH",   /* UNBALANCE_AIRFLOW */
	"UPDATEAKTIVIERUNG",   /* UPGRADE_ACTIVATION */
	"FALSCHES PASSWORT",   /* PASSWORD_INCORRECT */
	"SERIENNUM.",   /* SERIAL_ID */
	"FIRMWAREVERSION",   /* FIRMWARE_VERSION */
	"GERAETETYP",   /* UNIT_TYPE */
	"ZUBEHOERE",   /* ACCESSORY */
	"EINSTEL.",   /* SETTINGS */
	"SERVICE",   /* SERVICE */
	"INFO",   /* INFO */
	"SPRACHAUSWAHL",   /* SELECT_LANGUAGE */
	"M",   /* MONDAY_SHORTNAME */
	"D",   /* TUESDAY_SHORTNAME */
	"M",   /* WEBNESDAY_SHORTNAME */
	"D",   /* THURSDAY_SHORTNAME */
	"F",   /* FRIDAY_SHORTNAME */
	"S",   /* SATURDAY_SHORTNAME */
	"S",   /* SUNDAY_SHORTNAME */
	"EINF.",   /* PASTE */
	"KOP.",   /* COPY */
	"ERSTES ZEITPROGRAM",   /* SET_FIRST_RANGE */
	"ZWEITES ZEITPROGRAM",   /* SET_SECOND_RANGE */
	"DRITTES ZEITPROGRAM",   /* SET_THIRD_RANGE */
	"VIERTES ZEITPROGRAM",   /* SET_FOURTH_RANGE */
	"STARTZEIT",   /* START_TIME */
	"ENDZEIT",   /* END_TIME */
	"LUFTMENGE",   /* AIR_FLOW */
	"MONTAG",   /* MONDAY */
	"DIENSTAG",   /* TUESDAY */
	"MITTWOCH",   /* WEDNESDAY */
	"DONNERS.",   /* THURSDAY */
	"FREITAG",   /* FRIDAY */
	"SAMSTAG",   /* SATURDAY */
	"SONNTAG",   /* SUNDAY */
	"BENUTZE EINEN STIFT",   /* MAKE_USE_OF_A_STYLUS_PEN */
	"BLAUEN STRICH DRUECKEN",   /* PRESS_THE_BLUE_BAR */
	"AUSWAHL STUFENBETR.",   /* SELECT_SPEED_MODE */
	"3-STUFIG",   /* THREE_SPEED */
	"STUFENLOS",   /* STEPLESS */
	"AUSWAHL GESCHW.MIN.",   /* SELECT_SPEED_MIN */
	"AUSWAHL GESCHW.MIT.",   /* SELECT_SPEED_MED */
	"AUSWAHL GESCHW.MAX.",   /* SELECT_SPEED_MAX */
	"AUSWAHL FILTERZEIT",   /* SET_FILTER_TIME */
	"MONATE",   /* MONTHS */
	"VOLUMENSTR.EINSTEL.",   /* SET_UNBALANCE */
	"ZUR.",   /* BACK */
	"ZUBEHOERMANAGER",   /* ACCESSORY_MANAGER */
	"KLIMA EINSTEL.",   /* CLIMA_SETTINGS */
	"TEMP EINSTEL.",   /* TEMPERATURE_SETTINGS */
	"WOCHENPROGRAMMEINS.",   /* WEEKLY_SETTINGS */
	"PROGRAMM",   /* PROGRAM */
	"ANSICHT",   /* VIEW */
	"PROG",   /* PROG */
	"EINGE.ANZ. DER BER.",   /* SET_NBR_OF_RANGES */
	"ABLUFT",   /* RETURN */
	"EINHEIT",   /* UNIT */
	"SUCHEN...",   /* SEARCHING */
	"FEHLER",   /* ERROR */
	"EINHEIT NICHT GEFUNDEN",   /* UNIT_NOT_FOUND */
	"BITTE UBERPRUFEN SIE",   /* PLEASE_CHECK_THE */
	"DAS KABEL UND START.",   /* CABLE_AND_RESTART */
	"SIE DAS SYSTEM",   /* THE_SYSTEM */
	"VERBUNDEN",   /* CONNECTED */
	"DEAKTIV",   /* DISABLE */
	"TOUCH KALIBRIERT",   /* TOUCH_CALIBRATED */
	"WARNMELDUNG",   /* WARNINGS_REPORT */
	"WECHSELN SIE DIE FILTER",   /* RECOMMEND_TO_CHANGE_FILTERS */
	"PASSWORT KORREKT",   /* PASSWORD_CORRECT */
	"SON",   /* SUN */
	"MON",   /* MON */
	"DIE",   /* TUE */
	"MIT",   /* WED */
	"DON",   /* THU */
	"FRE",   /* FRI */
	"SAM",   /* SAT */
	"NC",   /* NC */
	"RH EINSTEL.",   /* RH_SETTINGS */
	"RH SCHWELLE EINSTEL",   /* SET_RH_THRESHOLD */
	"CO2 EINSTEL.",   /* CO2_SETTINGS */
	"   CO2    LUFTMENGE",   /* SET_CO2_THRESHOLD */
	"BEGEGNEN",   /* COUNTER */
	"PARTY EINSTELLUNG",   /* PARTY_SETTINGS */
	"PARTY ZEIT EINSTEL",   /* SET_PARTY_TIMER */
	"VERAN.",   /* EVENT */
	"WOCHE",   /* WEEK */
	"FUEHLER",   /* PROBES */
	"KONFIG",   /* CONFIG */
	"HYSTER. TEMP.SET.",   /* HYSTER_TEMPSET */
	"SOMMER",   /* SUMMER */
	"WINTER",   /* WINTER */
	"AUSSENLUFT",   /* TFRESH */
	"TEMPER. HYSTERESE",   /* TEMPERATURE_HYSTERESIS */
	"ZULUFT",   /* SUPPLY */
	"ABLUFT",   /* EXTRACT */
	"BETRIEBSDATEN",   /* REPORT_DATA */
	"DRUCKSENSOR:",   /* PRESSURE_SENSOR */
	"ANSCHLUSSZUSTAND:",   /* LEVEL_LINK_SENSOR */
	"SOLLDRUCK:",   /* SETPOINT_PRESSURE */
	"MESSDRUCK:",   /* MEASURE_PRESSURE */
	"MOTORLEISTUNG:",   /* SPEED_MOTORS */
	"ANGESCHLOSSEN",   /* CONNECT */
	"NICHT ANGESCHLOSSEN",   /* NOT_CONNECTED */
	"ZUBEHOER TRENNEN",   /* REMOVE_ACCESSORY */
	"TRENNUNG BESTAETIGEN",   /* CONFIRM_REMOVE */
	"T. ABLUFT",   /* TRETURN */
	"JA",   /* YES */
	"NEIN",   /* NO */
	"HANDBETRIEB",   /* MANUAL */
	"AUTOMATISCH",   /* AUTOMATIC */
	"OFFEN",   /* OPEN */
	"ZU",   /* CLOSED */
	"KLIMA",   /* CLIMA */
	"PASSWORT",   /* PASSWORD */
	"HEISS",   /* HOT */
	"KALT",   /* COLD */
	"RESET",   /* RESET */
	"INPUT EINSTELLUNG",   /* INPUT_CONFIG */
	"0V = STOP",   /* INPUT_CONFIG_0V_STOP */
	"10V = STOP",   /* INPUT_CONFIG_10V_STOP */
	"0V = OFFEN",   /* INPUT_CONFIG_0V_OPEN */
	"10V = OFFEN",   /* INPUT_CONFIG_10V_OPEN */
	"LUFTMENGEREG.",   /* INPUT_CONFIG_REG_AIR_FLOW */
	"OUTPUT EINSTELLUNG",   /* OUTPUT_CONFIG */
	"AUSWAHL STUFE TX",   /* SELECT_FRANCE_CLASSTX */
	"STUFE TX",   /* FRANCE_CLASSTX */
	"LUEFTUNG REGULIERUNG",   /* VENTILATION_CONTROL */
	"VOC EINSTELLUNG",   /* VOC_CONFIG */
	"TEMPERATUREN",   /* TEMPERATURE */
	"DREHGESCHWINDIGKEIT",   /* SPEED */
	"KLIMAKONTROL",   /* CLIMA_CONTROL */
	"DATENSCHREIBEN IN PROGRESS",   /* WRITING_DATA */
	"ABSPEICHERN ERFOLGT",   /* WRITING_DATA_COMPLETED */
	"FEHLER BEIM SPEICHERN",   /* WRITING_DATA_ERROR */
	"IN ALARM",   /* IN_ALARM */
	"EXTERNE STEUERUNG",   /* EXTERNAL_CONTROL */
	"FEHLERLISTE",   /* ERRORS_REPORT */
	"BEREICHEIN",   /* SET_RANGE */
	"MAN. AUS",   /* MANUAL_OFF */
	"MAN. EIN",   /* MANUAL_ON */
	"MAN. ZU",   /* MANUAL_CLOSE */
	"MAN. OFFEN",   /* MANUAL_OPEN */
	"AUT. AUS",   /* AUT_OFF */
	"AUT. EIN",   /* AUT_ON */
	"WECHSELND",   /* CHANGING */
	"MIN.",   /* MINUTE_ABBR */
	"LUEFTUNG KONFIGURATION",   /* AIRFLOW_CONFIG */
	"WASSER KTR.",   /* WATER_CK */
	"EREIGNIS WAEHLEN",   /* SELECT_EVENT */
	"BYPASS OFFEN",   /* BYPASS_OPEN */
	"BYPASS ZU",   /* BYPASS_CLOSE */
	"GERAET LAUFT",   /* UNIT_RUN */
	"FEHLERGERAET",   /* UNIT_FAULT */
	"AKTION WAEHLEN",   /* SELECT_ACTION */
	"ALTES PASSWORT",   /* OLD_PASSWORD */
	"NEUES PASSWORT",   /* NEW_PASSWORD */
	"NEUES PASSWORT WIEDERHOLEN",   /* REPEAT_NEW_PASSWORD */
	"BENUTZER PW WECHSELN",   /* CHANGE_END_USER_PASSWORD */
	"SERVICE PW WECHSELN",   /* CHANGE_SERVICE_PASSWORD */
	"PW WECHSELN",   /* CHANGE_PASSWORD */
	"PW EINSTELLUNG",   /* PASSWORD_SETTINGS */
	"DATEN GEAENDERT",   /* DATA_CHANGED */
	"SPEICHERN",   /* SAVE_CHANGES */
	"AENDERUNGEN SPEICHERN?",   /* CANCEL */
	"FUEHLER EINSTELLUNG",   /* PROBES_SETTINGS */
	"HEIZUNG",   /* HEATER */
	"KUEHLER",   /* COOLER */
	"TAGE",   /* DAYS */
	"ZUB AUSSTECKEN",   /* DISCONNECT_ACCESSORY */
	"ZUB. KLIMA",   /* BOXINFO_ACCESSORY_CLIMA */
	"HARDWARE VERSION MB",   /* MB_HARDWARE_VERSION */
	"SOFTWARE VERSION MB",   /* MB_SOFTWARE_VERSION */
	"VORHEIZUNG",   /* PREHEATER */
	"NACHHEIZUNG",   /* POSTHEATER */
	"INNER",   /* INTERNAL */
	"LUFTMENGE",   /* MEASURE_AIRFLOW */
	"MODBUS EINSTELLUNG",   /* MODBUS_SETTINGS */
	"ADRESSE",   /* MODBUS_ADDRESS */
	"STATUS",   /* MODBUS_STATUS */
	"GETRENNT",   /* DISCONNECTED */
	"BYPASS MIN. AUSSENTEMP.",   /* BYPASS_MIN_EXT_TEMPERATURE */
	"MODBUSAKTIV. DATENANSICHT VIA MODBUS",   /* DATA_AVAILABLE_FROM_MODBUS */
	"RFM KANAL",   /* RFM__CHANNEL */
	"RFM STATUS",   /* RFM__STATUS */
	"RFM KANALWECHSEL",   /* RFM__CHANGE_CHANNEL */
	"VERBUNDEN",   /* CONNECTING */
	"RFM KANAL FREI",   /* RFM__CHANNEL_FREE */
	"RFM KANAL BELEGT",   /* RFM__CHANNEL_BUSY */
	"RFM KANAL IN ARBEIT",   /* RFM__CHANNEL_INPROGRESS */
	"RFM ALARM KANAL BELEGT",   /* RFM__ALERT_CHANNEL_BUSY */
	"OK BESTAETIGEN FUER ERNEUTE VERB.",   /* CONNECT__RETRY_CONNECTION_MESSAGE */
	"RFM KANALKONTROLLE IN ARBEIT",   /* RFM__CHECKING_CHANNEL_IN_PROGRESS */
	"FEUERALARM",   /* FIREALARM_FIRE_ALARM */
	"REGELUNGSART HEIZUNG",   /* REFERENCE_T_SETTING */
	"SEK.",   /* SECOND_ABBR */
	"AUSWAHL ZIELTEMP.",   /* DXDSETTINGS_REFERENCEPROBE */
	"DELTA T EINSTELLUNG",   /* DXDSETTINGS_DELTATEMPERATURE */
	"VERZUG",   /* DXDSETTINGS_DELAY */
	"BYPASS VIA EXT. SIGNAL",   /* BYPASS_OPERATED_BY_EXT_INPUT */
	CLText_NoText,   /* CLText_CAP_CALIBRATION_PROCEDURE */
	CLText_NoText,   /* CAP_CALIBRATION_START_MESSAGE */
	CLText_NoText,   /* CAP_CALIBRATION_RUNNING_MESSAGE */
	CLText_NoText,   /* CAP_CALIBRATION_CONFIRMDATA_MESSAGE */
	CLText_NoText,   /* CLText_AUTOMATIC_ON_STANDBY */
	CLText_NoText,   /* FIREALARM_ALARM_ACTIVATED */
	CLText_NoText,   /* FIREALARM_ALARM_DEACTIVATED */
	CLText_NoText,   /* FIREALARM_CONFIGURATION */
	CLText_NoText,   /* FIREALARM_REARM_MESSAGE */
	CLText_NoText,   /* FIREALARM_REARM */
	CLText_NoText,   /* PARTY_MODE */
	CLText_NoText,   /* PROCEDURE_STARTING_MESSAGE */
	CLText_NoText,   /* PROCEDURE_RUNNING_MESSAGE */
	CLText_NoText,   /* PROCEDURE_COMPLETED_MESSAGE */
	CLText_NoText,   /* DPP_THRESHOLD */
	CLText_NoText,   /* DPP_CALIBRATION */
	CLText_NoText,   /* DPP_FILTER_LEVEL */
	"ALLES ZUB AUSSTECKEN", /* Disconnect all accessories */
};

