#include "CLLanguage_PL.h"

const char* gLanguage_PLTexts[ CLTextId__TEXT_COUNT ] =
{
	"BYPASS", /* CLText_BYPASS */
	"ODSZRAN.", /* CLText_DEFROST */
	"FILTRY", /* CLText_FILTERS */
	"MENU", /* CLText_MENU */
	"ZAPISZ", /* CLText_SAVE */
	"CZAS", /* CLText_TIME */
	"DATA", /* CLText_DATE */
	"WYBIERZ KTS", /* CLText_SELECT_KTS */
	"KONFIGURACJA STREFY INFORMACYJNEJ", /* CLText_CONFIG_BOX_INFO */
	"JEZYK", /* CLText_SELECTION_LANGUAGE */
	"WYGASZACZ EKRANU", /* CLText_CONFIG_SCREEN_SAVER */
	"ZAKTUALIZUJ", /* CLText_UPGRADE */
	"DATA I GODZINA", /* CLText_DATE_SETTINGS */
	"USTAWIENIA 3 PREDKOSCI", /* CLText_THREE_SPEED_SETTINGS */
	"PROGRAMATOR TYGODNIOWY", /* CLText_WEEKLY_PROGRAMMER */
	"KALIBRACJA WYSWIETLACZA", /* CLText_TOUCH_CALIBRATION */
	"FILTRY", /* CLText_FILTER_SETTINGS */
	"BYPASS", /* CLText_BPD_SETTINGS */
	"BALANS STRUMIENI", /* CLText_UNBALANCE_AIRFLOW */
	"AKTYWACJA AKTUALIZACJI", /* CLText_UPGRADE_ACTIVATION */
	"NIEPOPRAWNE HASLO", /* CLText_PASSWORD_INCORRECT */
	"NUMER SERYJNY", /* CLText_SERIAL_ID */
	"WERSJA OPROGR. KTS (FW)", /* CLText_FIRMWARE_VERSION */
	"MODEL URZADZENIA", /* CLText_UNIT_TYPE */
	"AKCESORIA", /* CLText_ACCESSORY */
	"USTAWIENIA", /* CLText_SETTINGS */
	"SERWIS", /* CLText_SERVICE */
	"INFORMACJE", /* CLText_INFO */
	"WYBIERZ JEZYK", /* CLText_SELECT_LANGUAGE */
	"P", /* CLText_MONDAY_SHORTNAME */
	"W", /* CLText_TUESDAY_SHORTNAME */
	"S", /* CLText_WEBNESDAY_SHORTNAME */
	"C", /* CLText_THURSDAY_SHORTNAME */
	"P", /* CLText_FRIDAY_SHORTNAME */
	"S", /* CLText_SATURDAY_SHORTNAME */
	"N", /* CLText_SUNDAY_SHORTNAME */
	"WKLEJ", /* CLText_PASTE */
	"KOPIUJ", /* CLText_COPY */
	"USTAW PIERWSZY ZAKRES", /* CLText_SET_FIRST_RANGE */
	"USTAW DRUGI ZAKRES", /* CLText_SET_SECOND_RANGE */
	"USTAW TRZECI ZAKRES", /* CLText_SET_THIRD_RANGE */
	"USTAW CZWARTY ZAKRES", /* CLText_SET_FOURTH_RANGE */
	"CZAS STARTU", /* CLText_START_TIME */
	"CZAS ZAKONCZENIA", /* CLText_END_TIME */
	"PRZEPLYW POWIETRZA", /* CLText_AIR_FLOW */
	"PONIEDZIALEK", /* CLText_MONDAY */
	"WTOREK", /* CLText_TUESDAY */
	"SRODA", /* CLText_WEDNESDAY */
	"CZWARTEK", /* CLText_THURSDAY */
	"PIATEK", /* CLText_FRIDAY */
	"SOBOTA", /* CLText_SATURDAY */
	"NIEDZIELA", /* CLText_SUNDAY */
	"UZYJ RYSIKA \"STYLUS PEN\"", /* CLText_MAKE_USE_OF_A_STYLUS_PEN */
	"WCISNIJ NIEBIESKI PRZYCISK", /* CLText_PRESS_THE_BLUE_BAR */
	"TRYB REGULACJI", /* CLText_SELECT_SPEED_MODE */
	"3 PREDKOSCI", /* CLText_THREE_SPEED */
	"PLYNNA", /* CLText_STEPLESS */
	"WYBIERZ PREDKOSC MIN.", /* CLText_SELECT_SPEED_MIN */
	"WYBIERZ PREDKOSC SREDN.", /* CLText_SELECT_SPEED_MED */
	"WYBIERZ PREDKOSC MAKS.", /* CLText_SELECT_SPEED_MAX */
	"USTAW CZAS WYMIANY/CZYSZCZENIA FILTROW", /* CLText_SET_FILTER_TIME */
	"MIESIACE", /* CLText_MONTHS */
	"USTAW BALANS STRUMIENI", /* CLText_SET_UNBALANCE */
	"WSTECZ", /* CLText_BACK */
	"MANAGER AKCESORIOW", /* CLText_ACCESSORY_MANAGER */
	"TEMPERATURA", /* CLText_CLIMA_SETTINGS */
	"USTAWIENIA TEMPERATURY", /* CLText_TEMPERATURE_SETTINGS */
	"USTAWIENIA TYGODNIOWE", /* CLText_WEEKLY_SETTINGS */
	"PROGRAMOWANIE", /* CLText_PROGRAM */
	"PODGLAD", /* CLText_VIEW */
	"PROGR", /* CLText_PROG */
	"USTAW LICZBE ZAKRESOW:", /* CLText_SET_NBR_OF_RANGES */
	"WYWIEW", /* CLText_RETURN */
	"REKU", /* CLText_UNIT */
	"TRWA SZUKANIE", /* CLText_SEARCHING */
	"BLAD", /* CLText_ERROR */
	"JEDNOSTKA NIE ZNALEZIONA", /* CLText_UNIT_NOT_FOUND */
	"PROSZE SPRAWDZ", /* CLText_PLEASE_CHECK_THE */
	"POLACZENIE KABL. I ZRESETUJ", /* CLText_CABLE_AND_RESTART */
	"SYSTEM", /* CLText_THE_SYSTEM */
	"PODLACZONY", /* CLText_CONNECTED */
	"NIEAKTYWNE", /* CLText_DISABLE */
	"WYSWIETLACZ SKALIBROWANY", /* CLText_TOUCH_CALIBRATED */
	"RAPORT OSTRZEZEN", /* CLText_WARNINGS_REPORT */
	"ZALECANA WYMIANA/CZYSZCZENIE FILTR\323W", /* CLText_RECOMMEND_TO_CHANGE_FILTERS */
	"HASLO POPRAWNE", /* CLText_PASSWORD_CORRECT */
	"NIE", /* CLText_SUN */
	"PON", /* CLText_MON */
	"WT", /* CLText_TUE */
	"SR", /* CLText_WED */
	"CZW", /* CLText_THU */
	"PT", /* CLText_FRI */
	"SOB", /* CLText_SAT */
	"NC", /* CLText_NC */
	"CZUJNIK WILGOTNOSCI", /* CLText_RH_SETTINGS */
	"USTAW PROG WILGOTNOSCI", /* CLText_SET_RH_THRESHOLD */
	"CZUJNIK CO2", /* CLText_CO2_SETTINGS */
	"    CO2         PRZEPLYW POWIETRZA", /* CLText_SET_CO2_THRESHOLD */
	"LICZNIK", /* CLText_COUNTER */
	"TRYB \"IMPREZA\"", /* CLText_PARTY_SETTINGS */
	"USTAW CZAS IMPREZY", /* CLText_SET_PARTY_TIMER */
	"ZDARZENIE", /* CLText_EVENT */
	"TYDZIEN", /* CLText_WEEK */
	"CZUJNIKI", /* CLText_PROBES */
	"KONFIGURACJA", /* CLText_CONFIG */
	"USTAW. HISTEREZE TEMPERATURY", /* CLText_HYSTER_TEMPSET */
	"LATO", /* CLText_SUMMER */
	"ZIMA", /* CLText_WINTER */
	"T.SWIEZ.POWIET.", /* CLText_TFRESH */
	"HISTEREZA TEMPERATURY", /* CLText_TEMPERATURE_HYSTERESIS */
	"NAWIEW", /* CLText_SUPPLY */
	"WYWIEW", /* CLText_EXTRACT */
	"RAPORT STATUSU", /* CLText_REPORT_DATA */
	"CZUJNIK CISNIENIA", /* CLText_PRESSURE_SENSOR */
	"POZIOM POLACZENIA", /* CLText_LEVEL_LINK_SENSOR */
	"ZADANE CISNIENIE", /* CLText_SETPOINT_PRESSURE */
	"ZMIERZONE CISNIENIE", /* CLText_MEASURE_PRESSURE */
	"PREDKOSC WENTYLATORA", /* CLText_SPEED_MOTORS */
	"PODLACZONE", /* CLText_CONNECT */
	"NIE PODLACZONE", /* CLText_NOT_CONNECTED */
	"USUN AKCESORIUM", /* CLText_REMOVE_ACCESSORY */
	"POTWIERDZ USUNIECIE", /* CLText_CONFIRM_REMOVE */
	"T.NA POWR.", /* CLText_TRETURN */
	"TAK", /* CLText_YES */
	"NIE", /* CLText_NO */
	"RECZNY", /* CLText_MANUAL */
	"AUTOMATYCZNY", /* CLText_AUTOMATIC_ON */
	"OTWARTY", /* CLText_OPEN */
	"ZAMKNIETY", /* CLText_CLOSED */
	"KLIMATYZACJA", /* CLText_CLIMA */
	"HASLO", /* CLText_PASSWORD */
	"OGRZ", /* CLText_HOT */
	"CH\243.", /* CLText_COLD */
	"RESET", /* CLText_RESET */
	"WEJSCIA SYGNALOWE", /* CLText_INPUT_CONFIG */
	"0V = STOP", /* CLText_INPUT_CONFIG_0V_STOP */
	"10V = STOP", /* CLText_INPUT_CONFIG_10V_STOP */
	"0V=OTWARTY", /* CLText_INPUT_CONFIG_0V_OPEN */
	"10V=OTWARTY", /* CLText_INPUT_CONFIG_10V_OPEN */
	"REGULACJA  PRZEPLYWU", /* CLText_INPUT_CONFIG_REG_AIR_FLOW */
	"WYJSCIA SYGNALOWE", /* CLText_OUTPUT_CONFIG */
	"WYBIERZ KLASE TX", /* CLText_SELECT_FRANCE_CLASSTX */
	"KLASA TX", /* CLText_FRANCE_CLASSTX */
	"TRYB PRACY", /* CLText_VENTILATION_CONTROL */
	"CZUJNIK JAKOSCI POWIETRZA (LZO)", /* CLText_VOC_CONFIG */
	"TEMPERATURA", /* CLText_TEMPERATURE */
	"PREDKOSC", /* CLText_SPEED */
	"KONTROLA KLIMATYZACJI", /* CLText_CLIMA_CONTROL */
	"TRWA ZAPIS DANYCH...", /* CLText_WRITING_DATA */
	"ZAKONCZONO ZAPISYWANIE", /* CLText_WRITING_DATA_COMPLETED */
	"BLAD ZAPISYWANIA", /* CLText_WRITING_DATA_ERROR */
	"STAN ALARMU", /* CLText_IN_ALARM */
	"KONTROLA ZEWNETRZNA", /* CLText_EXTERNAL_CONTROL */
	"RAPORT BLEDOW", /* CLText_ERRORS_REPORT */
	"UST. ZAKR.", /* CLText_SET_RANGE */
	"RECZNY-WYLACZONY", /* CLText_MANUAL_OFF */
	"RECZNY-ZALACZONY", /* CLText_MANUAL_ON */
	"RECZNY-ZAMKNIETY", /* CLText_MANUAL_CLOSE */
	"RECZNY-OTWARTY", /* CLText_MANUAL_OPEN */
	"AUTOMATYCZ-WYLACZONY", /* CLText_AUT_OFF */
	"AUTOMATYCZ-ZALACZONY", /* CLText_AUT_ON */
	"ZMIANA", /* CLText_CHANGING */
	"MIN.", /* CLText_MINUTE_ABBR */
	"KONFIGURACJA PRZEPLYWU", /* CLText_AIRFLOW_CONFIG */
	"WODA", /* CLText_WATER_CK */
	"WYBIERZ ZDARZENIE", /* CLText_SELECT_EVENT */
	"BAJPAS OTWARTY", /* CLText_BYPASS_OPEN */
	"BAJPAS ZAMKNIETY", /* CLText_BYPASS_CLOSE */
	"REKU PRACUJE", /* CLText_UNIT_RUN */
	"BLAD", /* CLText_UNIT_FAULT */
	"WYBIERZ AKCJE", /* CLText_SELECT_ACTION */
	"STARE HASLO", /* CLText_OLD_PASSWORD */
	"NOWE HASLO", /* CLText_NEW_PASSWORD */
	"POWTORZ NOWE HASLO", /* CLText_REPEAT_NEW_PASSWORD */
	"ZMIEN HASLO UZYTKOWNIKA", /* CLText_CHANGE_END_USER_PASSWORD */
	"ZMIEN HASLO SERWISOWE", /* CLText_CHANGE_SERVICE_PASSWORD */
	"ZMIEN HASLO", /* CLText_CHANGE_PASSWORD */
	"HASLO UZYTKOWNIKA", /* CLText_PASSWORD_SETTINGS */
	"DANE ZMIENIONE", /* CLText_DATA_CHANGED */
	"ZAPISAC ZMIANY?", /* CLText_SAVE_CHANGES */
	"ANULUJ", /* CLText_CANCEL */
	"USTAWIENIA CZUJNIKOW", /* CLText_PROBES_SETTINGS */
	"NAGRZEWNICA", /* CLText_HEATER */
	"CHLODNICA", /* CLText_COOLER */
	"DNI", /* CLText_DAYS */
	"ODLACZENIE AKCESORIOW", /* CLText_DISCONNECT_ACCESSORY */
	"AKCESORIA", /* CLText_BOXINFO_ACCESSORY_CLIMA */
	"WERSJA SPRZETU (MBH)", /* CLText_MB_HARDWARE_VERSION */
	"WERSJA OPROGR. (MBS)", /* CLText_MB_SOFTWARE_VERSION */
	"NAGRZEWNICA WSTEPNA", /* CLText_PREHEATER */
	"NAGRZEWNICA WTORNA", /* CLText_POSTHEATER */
	"WEWNETRZNY", /* CLText_INTERNAL */
	"ZMIERZONY PRZEPLYW", /* CLText_MEASURE_AIRFLOW */
	"MODBUS", /* CLText_MODBUS_SETTINGS */
	"ADRES", /* CLText_MODBUS_ADDRESS */
	"STATUS", /* CLText_MODBUS_STATUS */
	"ROZLACZONY", /* CLText_DISCONNECTED */
	"MIN. TEMP. ZEWNETRZNA", /* CLText_BYPASS_MIN_EXT_TEMPERATURE */
	"MODBUS AKTYWNY. INFORMACJE DOSTEPNE PRZEZ MODBUS.", /* CLText_DATA_AVAILABLE_FROM_MODBUS */
	"KANAL", /* CLText_RFM__CHANNEL */
	"STATUS", /* CLText_RFM__STATUS */
	"USTAW KANAL", /* CLText_RFM__CHANGE_CHANNEL */
	"LACZENIE", /* CLText_CONNECTING */
	"WOLNY", /* CLText_RFM__CHANNEL_FREE */
	"ZAJETY", /* CLText_RFM__CHANNEL_BUSY */
	"W TRAKCIE", /* CLText_RFM__CHANNEL_INPROGRESS */
	"KANAL ZAJETY. WYBIERZ INNY", /* CLText_RFM__ALERT_CHANNEL_BUSY */
	"WCISNIJ OK, BY PONOWIC PROBE.", /* CLText_CONNECT__RETRY_CONNECTION_MESSAGE */
	"TRWA SPRAWDZANIE KANALU", /* CLText_RFM__CHECKING_CHANNEL_IN_PROGRESS */
	"ALARM POZAROWY", /* CLText_FIREALARM_FIRE_ALARM */
	"TEMPERATURA REFERENCYJNA", /* CLText_REFERENCE_T_SETTING */
	"SEK.", /* CLText_SECOND_ABBR */
	"CZUJNIK REFERENCYJNY", /* CLText_DXDSETTINGS_REFERENCEPROBE */
	"DELTA T", /* CLText_DXDSETTINGS_DELTATEMPERATURE */
	"PROBKOWANIE", /* CLText_DXDSETTINGS_DELAY */
	"BAJPAS JEST STEROWANY ZEWNETRZNIE", /* CLText_BYPASS_OPERATED_BY_EXT_INPUT */
	"KALIBRACJA TRYBU STAL. CISN.", /* CLText_CAP_CALIBRATION_PROCEDURE */
	"OTWORZ WSZYSTKIE ZAWORY WENTYLACYJNE I WCISNIJ OK, GDY GOTOWE", /* CLText_CAP_CALIBRATION_START_MESSAGE */
	"TRWA KALIBRACJA.\rPROSZE CZEKAC", /* CLText_CAP_CALIBRATION_RUNNING_MESSAGE */
	"POTWIERDZ ZMIERZONE CISNIENIE", /* CLText_CAP_CALIBRATION_CONFIRMDATA_MESSAGE */
	"TRYB AUTOMATYCZNY", /* CLText_AUTOMATIC_ON_STANDBY */
	"ALARM POZAROWY WLACZONY", /* CLText_FIREALARM_ALARM_ACTIVATED */
	"ALARM POZAROWY WYLACZONY", /* CLText_FIREALARM_ALARM_DEACTIVATED */
	"KONFIGURACJA", /* CLText_FIREALARM_CONFIGURATION */
	"ABY WZNOWIC NORMALNY TRYB PRACY WCISCNIJ PRZYCISK RESET", /* CLText_FIREALARM_REARM_MESSAGE */
	"RESET", /* CLText_FIREALARM_REARM */
	"IMPREZA", /* CLText_PARTY_MODE */
	CLText_NoText, /* PROCEDURE_STARTING_MESSAGE */
	CLText_NoText, /* PROCEDURE_RUNNING_MESSAGE */
	CLText_NoText, /* PROCEDURE_COMPLETED_MESSAGE */
	CLText_NoText, /* DPP_THRESHOLD */
	CLText_NoText, /* DPP_CALIBRATION */
	CLText_NoText, /* DPP_FILTER_LEVEL */
	CLText_NoText, /* Disconnect all accessories */
};

