#include "CLLanguage_FR.h"

const char* gLanguage_FRTexts[ CLTextId__TEXT_COUNT ] =
{
	"BYPASS", /* CLText_BYPASS */
	"ANTIGEL", /* CLText_DEFROST */
	"FILTRES", /* CLText_FILTERS */
	"MENU", /* CLText_MENU */
	"ENREGISTRER", /* CLText_SAVE */
	"HEURE", /* CLText_TIME */
	"DATE:", /* CLText_DATE */
	"SELECT.KTS", /* CLText_SELECT_KTS */
	"PARAMETRE AFFICHAGE", /* CLText_CONFIG_BOX_INFO */
	"CHANGER LA LANGUE", /* CLText_SELECTION_LANGUAGE */
	"PARA.ECRAN DE VEILLE", /* CLText_CONFIG_SCREEN_SAVER */
	"MISE A JOUR", /* CLText_UPGRADE */
	"REGLAGE HORLOGE", /* CLText_DATE_SETTINGS */
	"REGLAGE 3 VITESSES", /* CLText_THREE_SPEED_SETTINGS */
	"PROGRAMM. HORAIRE", /* CLText_WEEKLY_PROGRAMMER */
	"ETALONNAGE ECRAN", /* CLText_TOUCH_CALIBRATION */
	"REGLAGE FILTRES", /* CLText_FILTER_SETTINGS */
	"REGLAGE BYPASS", /* CLText_BPD_SETTINGS */
	"DESEQUILIBRE DEBIT", /* CLText_UNBALANCE_AIRFLOW */
	"DEMARRER MAJ", /* CLText_UPGRADE_ACTIVATION */
	"MDP INCORRECT", /* CLText_PASSWORD_INCORRECT */
	"N\260 DE SERIE", /* CLText_SERIAL_ID */
	"VERSION FIRMWARE", /* CLText_FIRMWARE_VERSION */
	"TYPE UNITE", /* CLText_UNIT_TYPE */
	"ACCESSOIRES", /* CLText_ACCESSORY */
	"REGLAGES", /* CLText_SETTINGS */
	"SERVICE", /* CLText_SERVICE */
	"INFO", /* CLText_INFO */
	"CHOIX DE LA LANGUE", /* CLText_SELECT_LANGUAGE */
	"L", /* CLText_MONDAY_SHORTNAME */
	"M", /* CLText_TUESDAY_SHORTNAME */
	"M", /* CLText_WEBNESDAY_SHORTNAME */
	"J", /* CLText_THURSDAY_SHORTNAME */
	"V", /* CLText_FRIDAY_SHORTNAME */
	"S", /* CLText_SATURDAY_SHORTNAME */
	"D", /* CLText_SUNDAY_SHORTNAME */
	"COLLER", /* CLText_PASTE */
	"COPIER", /* CLText_COPY */
	"SELEC. PLAGE 1", /* CLText_SET_FIRST_RANGE */
	"SELEC. PLAGE 2", /* CLText_SET_SECOND_RANGE */
	"SELEC. PLAGE 3", /* CLText_SET_THIRD_RANGE */
	"SELEC. PLAGE 4", /* CLText_SET_FOURTH_RANGE */
	"DEBUT EVENEMENT", /* CLText_START_TIME */
	"FIN EVENEMENT", /* CLText_END_TIME */
	"DEBIT", /* CLText_AIR_FLOW */
	"LUNDI", /* CLText_MONDAY */
	"MARDI", /* CLText_TUESDAY */
	"MERCREDI", /* CLText_WEDNESDAY */
	"JEUDI", /* CLText_THURSDAY */
	"VENDRED", /* CLText_FRIDAY */
	"SAMEDI", /* CLText_SATURDAY */
	"DIMANCHE", /* CLText_SUNDAY */
	"UTILISER UN STYLET", /* CLText_MAKE_USE_OF_A_STYLUS_PEN */
	"APPUYER SUR LA BARRE BLEU", /* CLText_PRESS_THE_BLUE_BAR */
	"SELECTION. LE MODE", /* CLText_SELECT_SPEED_MODE */
	"3 VITESSES", /* CLText_THREE_SPEED */
	"VARIBALE", /* CLText_STEPLESS */
	"CHOIX VITESSE MIN", /* CLText_SELECT_SPEED_MIN */
	"CHOIX VITESSE MOY", /* CLText_SELECT_SPEED_MED */
	"CHOIX VITESSE MAX", /* CLText_SELECT_SPEED_MAX */
	"REGL. TIMER FILTRE", /* CLText_SET_FILTER_TIME */
	"MOIS", /* CLText_MONTHS */
	"REGLER DESEQUILIBR", /* CLText_SET_UNBALANCE */
	"RETOUR", /* CLText_BACK */
	"GESTION ACCESSOIRES", /* CLText_ACCESSORY_MANAGER */
	"REGLER CLIMAT", /* CLText_CLIMA_SETTINGS */
	"SEUIL DE TEMPERATURE", /* CLText_TEMPERATURE_SETTINGS */
	"PROGRAMM. HORAIRE", /* CLText_WEEKLY_SETTINGS */
	"PROGRAMME", /* CLText_PROGRAM */
	"VOIR", /* CLText_VIEW */
	"PROG", /* CLText_PROG */
	"SELEC. NB DE PLAGE:", /* CLText_SET_NBR_OF_RANGES */
	"RETOUR", /* CLText_RETURN */
	"UNITE", /* CLText_UNIT */
	"CHARGEMENT..", /* CLText_SEARCHING */
	"ERREUR", /* CLText_ERROR */
	"UNITE NON TROUVEE", /* CLText_UNIT_NOT_FOUND */
	"VERIFIER LE", /* CLText_PLEASE_CHECK_THE */
	"BRANCH.ET REDEMAR", /* CLText_CABLE_AND_RESTART */
	"LE SYSTEME", /* CLText_THE_SYSTEM */
	"CONNECTE", /* CLText_CONNECTED */
	"DESACTIVE", /* CLText_DISABLE */
	"TOUCHE CALIBREE", /* CLText_TOUCH_CALIBRATED */
	"RAPPORT ALARMES:", /* CLText_WARNINGS_REPORT */
	"FILTRE A CHANGER", /* CLText_RECOMMEND_TO_CHANGE_FILTERS */
	"MOT DE PASSE OK", /* CLText_PASSWORD_CORRECT */
	"DIM", /* CLText_SUN */
	"LUN", /* CLText_MON */
	"MAR", /* CLText_TUE */
	"MER", /* CLText_WED */
	"JEU", /* CLText_THU */
	"VEN", /* CLText_FRI */
	"SAM", /* CLText_SAT */
	"NC", /* CLText_NC */
	"PARAMETRE HUMIDITE", /* CLText_RH_SETTINGS */
	"PARAM. NIVEAU HR", /* CLText_SET_RH_THRESHOLD */
	"PARAMETRE CO2", /* CLText_CO2_SETTINGS */
	"    CO2      DEBIT", /* CLText_SET_CO2_THRESHOLD */
	"COMPTEUR", /* CLText_COUNTER */
	"SURVENTILATION", /* CLText_PARTY_SETTINGS */
	"DUREE SURVENTIL:", /* CLText_SET_PARTY_TIMER */
	"EVENN.", /* CLText_EVENT */
	"SEMA.", /* CLText_WEEK */
	"SONDES", /* CLText_PROBES */
	"CONFIG", /* CLText_CONFIG */
	"HYSTERESIS TEMP.", /* CLText_HYSTER_TEMPSET */
	"ETE", /* CLText_SUMMER */
	"HIVER", /* CLText_WINTER */
	"T AN", /* CLText_TFRESH */
	"TEMPER. HYSTERESIS", /* CLText_TEMPERATURE_HYSTERESIS */
	"SOUFFLAGE", /* CLText_SUPPLY */
	"EXTRATION", /* CLText_EXTRACT */
	"DONNEES RAPPORT", /* CLText_REPORT_DATA */
	"CAPTEUR PRESSION:", /* CLText_PRESSURE_SENSOR */
	"VALEUR CAPTEUR:", /* CLText_LEVEL_LINK_SENSOR */
	"CONSIGNE PRESSION:", /* CLText_SETPOINT_PRESSURE */
	"PRESSION MESUREE:", /* CLText_MEASURE_PRESSURE */
	"MOTEURS A VITESSE:", /* CLText_SPEED_MOTORS */
	"CONNECTE", /* CLText_CONNECT */
	"NON CONNECTE", /* CLText_NOT_CONNECTED */
	"ENLEVER ACCESSOIRES", /* CLText_REMOVE_ACCESSORY */
	"VALIDER SUPPRESSION", /* CLText_CONFIRM_REMOVE */
	"T. RETOUR", /* CLText_TRETURN */
	"OUI", /* CLText_YES */
	"NON", /* CLText_NO */
	"MANUEL", /* CLText_MANUAL */
	"AUTOMATIQUE", /* CLText_AUTOMATIC_ON */
	"OUVERT", /* CLText_OPEN */
	"FERME", /* CLText_CLOSED */
	"CLIMAT", /* CLText_CLIMA */
	"MOT DE PASSE", /* CLText_PASSWORD */
	"CHAUD", /* CLText_HOT */
	"FROID", /* CLText_COLD */
	"RESET", /* CLText_RESET */
	"CONFIG. ENTREE", /* CLText_INPUT_CONFIG */
	"0V = STOP", /* CLText_INPUT_CONFIG_0V_STOP */
	"10V = STOP", /* CLText_INPUT_CONFIG_10V_STOP */
	"0V = OUVERT", /* CLText_INPUT_CONFIG_0V_OPEN */
	"10V = OUVERT", /* CLText_INPUT_CONFIG_10V_OPEN */
	"REG DEBIT D'AIR", /* CLText_INPUT_CONFIG_REG_AIR_FLOW */
	"CONFIG. SORTIE", /* CLText_OUTPUT_CONFIG */
	"CHOIX TYPE LOGE.", /* CLText_SELECT_FRANCE_CLASSTX */
	"TYPE LOGE.", /* CLText_FRANCE_CLASSTX */
	"CONTROLE VENTIL", /* CLText_VENTILATION_CONTROL */
	"CONFIG. VOC", /* CLText_VOC_CONFIG */
	"TEMPERATURE", /* CLText_TEMPERATURE */
	"VITESSE", /* CLText_SPEED */
	"CONTROL CLIMAT", /* CLText_CLIMA_CONTROL */
	"CHARG. DONNEES ENN COURS", /* CLText_WRITING_DATA */
	"DONNEES CHARGEES", /* CLText_WRITING_DATA_COMPLETED */
	"ERREUR DE CHARGEMENT", /* CLText_WRITING_DATA_ERROR */
	"ALARME", /* CLText_IN_ALARM */
	"CONTROLE EXTERNE", /* CLText_EXTERNAL_CONTROL */
	"LISTE ERREURS", /* CLText_ERRORS_REPORT */
	"REGL. PLAGE", /* CLText_SET_RANGE */
	"MANU.ON", /* CLText_MANUAL_OFF */
	"MANU.OFF", /* CLText_MANUAL_ON */
	"MAN.FERME", /* CLText_MANUAL_CLOSE */
	"MANU.OUVERT", /* CLText_MANUAL_OPEN */
	"AUTO.OFF", /* CLText_AUT_OFF */
	"AUTO.OFF", /* CLText_AUT_ON */
	"CHANGER", /* CLText_CHANGING */
	"MIN.", /* CLText_MINUTE_ABBR */
	"REGL. DEBIT", /* CLText_AIRFLOW_CONFIG */
	"BATT EAU", /* CLText_WATER_CK */
	"SELECT EVENEMENT", /* CLText_SELECT_EVENT */
	"BYPASS OUVERT", /* CLText_BYPASS_OPEN */
	"BYPASS FERME", /* CLText_BYPASS_CLOSE */
	"UNITE EN MARCHE", /* CLText_UNIT_RUN */
	"UNITE DEFAUT", /* CLText_UNIT_FAULT */
	"CHOISIR ACTION", /* CLText_SELECT_ACTION */
	"ANCIEN MDP", /* CLText_OLD_PASSWORD */
	"NOUVEAU MDP", /* CLText_NEW_PASSWORD */
	"CONFIRMER NOUV. MDP", /* CLText_REPEAT_NEW_PASSWORD */
	"CHANGER MDP UTIL.", /* CLText_CHANGE_END_USER_PASSWORD */
	"CHANGER MDP SERVICE", /* CLText_CHANGE_SERVICE_PASSWORD */
	"CHANGER MDP", /* CLText_CHANGE_PASSWORD */
	"REGL MDP", /* CLText_PASSWORD_SETTINGS */
	"DONNEES MODIFIEES", /* CLText_DATA_CHANGED */
	"ENR. MODIFS", /* CLText_SAVE_CHANGES */
	"ANNULER", /* CLText_CANCEL */
	"REGL. SONDES", /* CLText_PROBES_SETTINGS */
	"CHAUFFAGE", /* CLText_HEATER */
	"RAFRAICHISSEMENT", /* CLText_COOLER */
	"JOURNEES", /* CLText_DAYS */
	"DEBRANCH. ACC.", /* CLText_DISCONNECT_ACCESSORY */
	"ACC. CLIMAT", /* CLText_BOXINFO_ACCESSORY_CLIMA */
	"VERSION MB DU HARDWARE", /* CLText_MB_HARDWARE_VERSION */
	"VERSION MB DU SOFTWARE", /* CLText_MB_SOFTWARE_VERSION */
	"PRECHAUFFAGE", /* CLText_PREHEATER */
	"POST CHAUFFAGE", /* CLText_POSTHEATER */
	"INTERIEUR", /* CLText_INTERNAL */
	"DEBIT", /* CLText_MEASURE_AIRFLOW */
	"REGLAGE MODBUS", /* CLText_MODBUS_SETTINGS */
	"ADRESSE", /* CLText_MODBUS_ADDRESS */
	"ETAT ", /* CLText_MODBUS_STATUS */
	"DECONNECTE", /* CLText_DISCONNECTED */
	"TEMPERATURE EXTERIEURE MINIMALE BY PASS", /* CLText_BYPASS_MIN_EXT_TEMPERATURE */
	"MODBUS ACTIV\311. DONNEES DISPONIBLES POUR MODBUS.", /* CLText_DATA_AVAILABLE_FROM_MODBUS */
	"CANAL", /* CLText_RFM__CHANNEL */
	"ETAT ", /* CLText_RFM__STATUS */
	"CHANGER CANAL RFM", /* CLText_RFM__CHANGE_CHANNEL */
	"CONNEXION", /* CLText_CONNECTING */
	"LIBRE", /* CLText_RFM__CHANNEL_FREE */
	"OCCUPE", /* CLText_RFM__CHANNEL_BUSY */
	"EN COURS", /* CLText_RFM__CHANNEL_INPROGRESS */
	"CANAL RFM OCCUPE. CHANGER DE CANAL", /* CLText_RFM__ALERT_CHANNEL_BUSY */
	"APPUYER SUR OK POUR RELANCER LA CONNEXION", /* CLText_CONNECT__RETRY_CONNECTION_MESSAGE */
	"CONTROLER LE CANAL RFM EN COURS", /* CLText_RFM__CHECKING_CHANNEL_IN_PROGRESS */
	"ALARME INCENDIE", /* CLText_FIREALARM_FIRE_ALARM */
	"CHOIX SONDE TEMP.", /* CLText_REFERENCE_T_SETTING */
	"SEC.", /* CLText_SECOND_ABBR */
	"SONDE REFERENCE", /* CLText_DXDSETTINGS_REFERENCEPROBE */
	"DELTA TEMPERATURE", /* CLText_DXDSETTINGS_DELTATEMPERATURE */
	"DELAI", /* CLText_DXDSETTINGS_DELAY */
	"BY-PASS DEFINI PAR L'ENTREE EXTERNE", /* CLText_BYPASS_OPERATED_BY_EXT_INPUT */
	"PROCEDURE DE CALIBRAGE DU CAP", /* CLText_CAP_CALIBRATION_PROCEDURE */
	"OUVRIR TOUTES LES CLAPETS DE L'INSTALLATION, QUAND TOUT EST PRET, CLIQUEZ SUR LE BOUTON OK", /* CLText_CAP_CALIBRATION_START_MESSAGE */
	"CALIBRAGE EN COURS, VEUILLEZ PATIENTER...", /* CLText_CAP_CALIBRATION_RUNNING_MESSAGE */
	"CONFIRMER LA PRESSION DETECTEE?", /* CLText_CAP_CALIBRATION_CONFIRMDATA_MESSAGE */
	"AUTOMATIQUE (ON + STANDBY)", /* CLText_AUTOMATIC_ON_STANDBY */
	"ALARME INCENDIE ACTIVEE", /* CLText_FIREALARM_ALARM_ACTIVATED */
	"ALARME INCENDIE INACTIVE", /* CLText_FIREALARM_ALARM_DEACTIVATED */
	"CONFIGURATION ALARME FUMEE", /* CLText_FIREALARM_CONFIGURATION */
	"L\222UNITE PEUT ETRE REDEMARREE AVEC BOUTON REINITIALISATION MANUEL", /* CLText_FIREALARM_REARM_MESSAGE */
	"REARM.", /* CLText_FIREALARM_REARM */
	"BOOST", /* CLText_PARTY_MODE */
	"VOULEZ-VOUS LANCER LA PROCEDURE?", /* PROCEDURE_STARTING_MESSAGE */
	"PROCEDURE EN COURS...", /* PROCEDURE_RUNNING_MESSAGE */
	"PROCEDURE TERMINEE", /* PROCEDURE_COMPLETED_MESSAGE */
	"SEUIL", /* DPP_THRESHOLD */
	"CALIBRAGE", /* DPP_CALIBRATION */
	"NIVEAU DE FILTRE", /* DPP_FILTER_LEVEL */
 	"DECONNECTER TOUT", /* Disconnect all accessories */
	"DELAI MAJ DSC", /* DSC Memory card update delay */
	"REGLAGE PIR", /* PIR update delay */
    "CODE QR", /* QR Code */
    "ETAT CAPTEUR:",
    "VALEUR CO2:",
    "VALEUR VOC:",
    "VALEUR RH:",
    "PRECISION:",
    "QUALITE DE L'AIR(IAQ):",
    "PRECISION IAQ:",
    "REGLAGE CLEAN EVENT",
    "JOURS.",
    "DUREE CLEAN EVT:",
};

