#include "CLLanguage_NL.h"

const char* gLanguage_NLTexts[ CLTextId__TEXT_COUNT ] =
{
	"BYPASS", /* CLText_BYPASS */
	"ONTDOOIEN", /* CLText_DEFROST */
	"FILTERS", /* CLText_FILTERS */
	"MENU", /* CLText_MENU */
	"OPSLAAN", /* CLText_SAVE */
	"TIJD", /* CLText_TIME */
	"DATUM", /* CLText_DATE */
	"KEUZETOETS", /* CLText_SELECT_KTS */
	"SET BOX INFO", /* CLText_CONFIG_BOX_INFO */
	"TAALINSTELLINGEN", /* CLText_SELECTION_LANGUAGE */
	"SCREENSAVER INSTELLINGEN", /* CLText_CONFIG_SCREEN_SAVER */
	"UPDATE", /* CLText_UPGRADE */
	"DATUM INSTELLINGEN", /* CLText_DATE_SETTINGS */
	"3-TOERENTAL INSTELLINGEN", /* CLText_THREE_SPEED_SETTINGS */
	"WEEKPROGRAMMA", /* CLText_WEEKLY_PROGRAMMER */
	"TOUCH CALIBRATIE", /* CLText_TOUCH_CALIBRATION */
	"FILTER INSTELLINGEN", /* CLText_FILTER_SETTINGS */
	"BYPASS INSTELLINGEN", /* CLText_BPD_SETTINGS */
	"ONBALANS LUCHTSTROOM", /* CLText_UNBALANCE_AIRFLOW */
	"UPDATE ACTIVERING", /* CLText_UPGRADE_ACTIVATION */
	"ONJUIST WACHTWOORD", /* CLText_PASSWORD_INCORRECT */
	"SERIENUMMER", /* CLText_SERIAL_ID */
	"FIRMWARE VERSIE", /* CLText_FIRMWARE_VERSION */
	"UNIT TYPE", /* CLText_UNIT_TYPE */
	"ACCESSOIRES", /* CLText_ACCESSORY */
	"INSTELLINGEN", /* CLText_SETTINGS */
	"SERVICE", /* CLText_SERVICE */
	"INFORMATIE", /* CLText_INFO */
	"SELECTEER TAAL", /* CLText_SELECT_LANGUAGE */
	"M", /* CLText_MONDAY_SHORTNAME */
	"D", /* CLText_TUESDAY_SHORTNAME */
	"W", /* CLText_WEBNESDAY_SHORTNAME */
	"D", /* CLText_THURSDAY_SHORTNAME */
	"V", /* CLText_FRIDAY_SHORTNAME */
	"Z", /* CLText_SATURDAY_SHORTNAME */
	"Z", /* CLText_SUNDAY_SHORTNAME */
	"PLAKKEN", /* CLText_PASTE */
	"KOPI\313REN", /* CLText_COPY */
	"1E TIJDPROGRAMMA", /* CLText_SET_FIRST_RANGE */
	"2E TIJDPROGRAMMA", /* CLText_SET_SECOND_RANGE */
	"3E TIJDPROGRAMMA", /* CLText_SET_THIRD_RANGE */
	"4E TIJDPROGRAMMA", /* CLText_SET_FOURTH_RANGE */
	"STARTTIJD", /* CLText_START_TIME */
	"EINDTIJD", /* CLText_END_TIME */
	"LUCHTHOEVEELHEID", /* CLText_AIR_FLOW */
	"MAANDAG", /* CLText_MONDAY */
	"DINSDAG", /* CLText_TUESDAY */
	"WOENSDAG", /* CLText_WEDNESDAY */
	"DONDERDAG", /* CLText_THURSDAY */
	"VRIJDAG", /* CLText_FRIDAY */
	"ZATERDAG", /* CLText_SATURDAY */
	"ZONDAG", /* CLText_SUNDAY */
	"GEBRUIK STYLUS PEN", /* CLText_MAKE_USE_OF_A_STYLUS_PEN */
	"DRUK OP BLAUWE BALK", /* CLText_PRESS_THE_BLUE_BAR */
	"SELECTEER SNELHEID", /* CLText_SELECT_SPEED_MODE */
	"3-TOEREN", /* CLText_THREE_SPEED */
	"TRAPLOOS", /* CLText_STEPLESS */
	"KIES MIN. SNELHEID", /* CLText_SELECT_SPEED_MIN */
	"KIES GEM. SNELHEID", /* CLText_SELECT_SPEED_MED */
	"KIES MAX. SNELHEID", /* CLText_SELECT_SPEED_MAX */
	"SELECTEER FILTERTIJD", /* CLText_SET_FILTER_TIME */
	"MAANDEN", /* CLText_MONTHS */
	"SELECTEER ONBALANS", /* CLText_SET_UNBALANCE */
	"TERUG", /* CLText_BACK */
	"ACCESSOIRES", /* CLText_ACCESSORY_MANAGER */
	"KLIMAATINSTELLINGEN", /* CLText_CLIMA_SETTINGS */
	"TEMP. INSTELLINGEN", /* CLText_TEMPERATURE_SETTINGS */
	"WEEKINSTELLINGEN", /* CLText_WEEKLY_SETTINGS */
	"PROGRAMMA", /* CLText_PROGRAM */
	"WEERGEVEN", /* CLText_VIEW */
	"PROG", /* CLText_PROG */
	"SELECTEER AANTAL RANGES", /* CLText_SET_NBR_OF_RANGES */
	"RETOURLUCHT", /* CLText_RETURN */
	"UNIT", /* CLText_UNIT */
	"ZOEKEN.....", /* CLText_SEARCHING */
	"FOUT", /* CLText_ERROR */
	"UNIT NIET GEVONDEN", /* CLText_UNIT_NOT_FOUND */
	"CONTROLEER", /* CLText_PLEASE_CHECK_THE */
	"KABEL EN HERSTART", /* CLText_CABLE_AND_RESTART */
	"SYSTEEM", /* CLText_THE_SYSTEM */
	"VERBONDEN", /* CLText_CONNECTED */
	"UITGESCHAKELD", /* CLText_DISABLE */
	"TOUCH GECALIBREERD", /* CLText_TOUCH_CALIBRATED */
	"ALARMHISTORIE", /* CLText_WARNINGS_REPORT */
	"ADVIES FILTERS VERVANGEN", /* CLText_RECOMMEND_TO_CHANGE_FILTERS */
	"WACHTWOORD CORRECT", /* CLText_PASSWORD_CORRECT */
	"ZO", /* CLText_SUN */
	"MA", /* CLText_MON */
	"DI", /* CLText_TUE */
	"WO", /* CLText_WED */
	"DO", /* CLText_THU */
	"VR", /* CLText_FRI */
	"ZA", /* CLText_SAT */
	"NC", /* CLText_NC */
	"RV INSTELLINGEN", /* CLText_RH_SETTINGS */
	"KIES RV DREMPELWAARDE", /* CLText_SET_RH_THRESHOLD */
	"CO2 INSTELLINGEN", /* CLText_CO2_SETTINGS */
	"    CO2             LUCHTHOEVEELHEID", /* CLText_SET_CO2_THRESHOLD */
	"TELLER", /* CLText_COUNTER */
	"PARTY INSTELLINGEN", /* CLText_PARTY_SETTINGS */
	"KIES PARTY TIMER", /* CLText_SET_PARTY_TIMER */
	"EVENEMENT", /* CLText_EVENT */
	"WEEK", /* CLText_WEEK */
	"SONDES", /* CLText_PROBES */
	"CONFIG", /* CLText_CONFIG */
	"HYSTER. TEMP.SET.", /* CLText_HYSTER_TEMPSET */
	"ZOMER", /* CLText_SUMMER */
	"WINTER", /* CLText_WINTER */
	"T BUITENLUCHT", /* CLText_TFRESH */
	"TEMPER. HYSTERESE", /* CLText_TEMPERATURE_HYSTERESIS */
	"TOEVOER", /* CLText_SUPPLY */
	"AFVOER", /* CLText_EXTRACT */
	"REPORT DATA", /* CLText_REPORT_DATA */
	"DRUKSENSOR:", /* CLText_PRESSURE_SENSOR */
	"LEVEL SENSOR:", /* CLText_LEVEL_LINK_SENSOR */
	"NOMINALE DRUK:", /* CLText_SETPOINT_PRESSURE */
	"GEMETEN DRUK:", /* CLText_MEASURE_PRESSURE */
	"SNELHEID MOTOREN:", /* CLText_SPEED_MOTORS */
	"VERBONDEN", /* CLText_CONNECT */
	"NIET VERBONDEN", /* CLText_NOT_CONNECTED */
	"ACCESSOIRE VERWIJDEREN", /* CLText_REMOVE_ACCESSORY */
	"VERWIJDEREN BEVESTIGEN?", /* CLText_CONFIRM_REMOVE */
	"T. RETOUR", /* CLText_TRETURN */
	"JA", /* CLText_YES */
	"NEE", /* CLText_NO */
	"MANUEEL", /* CLText_MANUAL */
	"AUTOMATISCH", /* CLText_AUTOMATIC_ON */
	"OPEN", /* CLText_OPEN */
	"GESLOTEN", /* CLText_CLOSED */
	"KLIMAAT", /* CLText_CLIMA */
	"WACHTWOORD", /* CLText_PASSWORD */
	"WARM", /* CLText_HOT */
	"KOUD", /* CLText_COLD */
	"RESET", /* CLText_RESET */
	"INPUT INSTELLINGEN", /* CLText_INPUT_CONFIG */
	"0V = STOP", /* CLText_INPUT_CONFIG_0V_STOP */
	"10V = STOP", /* CLText_INPUT_CONFIG_10V_STOP */
	"0V = OPEN", /* CLText_INPUT_CONFIG_0V_OPEN */
	"10V = OPEN", /* CLText_INPUT_CONFIG_10V_OPEN */
	"REG LUCHTHOEVEELHEID", /* CLText_INPUT_CONFIG_REG_AIR_FLOW */
	"OUTPUT INSTELLINGEN", /* CLText_OUTPUT_CONFIG */
	"SELECTEER KLASSE TX", /* CLText_SELECT_FRANCE_CLASSTX */
	"KLASSE TX", /* CLText_FRANCE_CLASSTX */
	"VENTILATIE CONTROLE", /* CLText_VENTILATION_CONTROL */
	"VOC INSTELLINGEN", /* CLText_VOC_CONFIG */
	"TEMPERATUREN", /* CLText_TEMPERATURE */
	"SNELHEID  ", /* CLText_SPEED */
	"KLIMAATCONTROLE", /* CLText_CLIMA_CONTROL */
	"BIJWERKEN DATA\205", /* CLText_WRITING_DATA */
	"BIJWERKEN DATA KLAAR", /* CLText_WRITING_DATA_COMPLETED */
	"FOUT TIJDENS BIJWERKEN DATA", /* CLText_WRITING_DATA_ERROR */
	"IN ALARM", /* CLText_IN_ALARM */
	"EXTERNE CONTROLE", /* CLText_EXTERNAL_CONTROL */
	"ALARMLIJST", /* CLText_ERRORS_REPORT */
	"KIES BEREIK", /* CLText_SET_RANGE */
	"MAN. UIT", /* CLText_MANUAL_OFF */
	"MAN. AAN", /* CLText_MANUAL_ON */
	"MAN. GESLOTEN", /* CLText_MANUAL_CLOSE */
	"MAN. OPEN", /* CLText_MANUAL_OPEN */
	"AUT. UIT", /* CLText_AUT_OFF */
	"AUT. AAN", /* CLText_AUT_ON */
	"WIJZIGEN", /* CLText_CHANGING */
	"MIN.", /* CLText_MINUTE_ABBR */
	"LUCHTHOEVEELHEID INSTELLINGEN", /* CLText_AIRFLOW_CONFIG */
	"WATER CK", /* CLText_WATER_CK */
	"KIES OPTIE", /* CLText_SELECT_EVENT */
	"BYPASS OPEN", /* CLText_BYPASS_OPEN */
	"BYPASS GESLOTEN", /* CLText_BYPASS_CLOSE */
	"UNIT OPERATIONEEL", /* CLText_UNIT_RUN */
	"UNIT FOUT", /* CLText_UNIT_FAULT */
	"KIES ACTIE", /* CLText_SELECT_ACTION */
	"OUD WACHTWOORD", /* CLText_OLD_PASSWORD */
	"NIEUW WACHTWOORD", /* CLText_NEW_PASSWORD */
	"HERHAAL NIEUW WACHTWOORD", /* CLText_REPEAT_NEW_PASSWORD */
	"WIJZIG GEBRUIKER WACHTWOORD", /* CLText_CHANGE_END_USER_PASSWORD */
	"WIJZIG SERVICE WACHTWOORD", /* CLText_CHANGE_SERVICE_PASSWORD */
	"WIJZIG WACHTWOORD", /* CLText_CHANGE_PASSWORD */
	"WACHTWOORD INSTELLINGEN", /* CLText_PASSWORD_SETTINGS */
	"DATA GEWIJZIGD", /* CLText_DATA_CHANGED */
	"WIJZIGINGEN OPSLAAN", /* CLText_SAVE_CHANGES */
	"ANNULEREN", /* CLText_CANCEL */
	"SONDES INSTELLINGEN", /* CLText_PROBES_SETTINGS */
	"VERWARMER", /* CLText_HEATER */
	"KOELER", /* CLText_COOLER */
	"DAGEN", /* CLText_DAYS */
	"ACCESSOIRES UITSCHAKELEN", /* CLText_DISCONNECT_ACCESSORY */
	"ACCESSOIRES KLIMAAT", /* CLText_BOXINFO_ACCESSORY_CLIMA */
	"MB HARDWARE VERSIE", /* CLText_MB_HARDWARE_VERSION */
	"MB SOFTWARE VERSIE", /* CLText_MB_SOFTWARE_VERSION */
	"VOORVERWARMER", /* CLText_PREHEATER */
	"NAVERWARMER", /* CLText_POSTHEATER */
	"INTERN", /* CLText_INTERNAL */
	"LUCHTHOEVEELHEID", /* CLText_MEASURE_AIRFLOW */
	"MODBUS INSTELLINGEN", /* CLText_MODBUS_SETTINGS */
	"ADRES", /* CLText_MODBUS_ADDRESS */
	"STATUS", /* CLText_MODBUS_STATUS */
	"UITGESCHAKELD", /* CLText_DISCONNECTED */
	"MIN. BUITENTEMPERATUUR BYPASS", /* CLText_BYPASS_MIN_EXT_TEMPERATURE */
	"MODBUS ACTIEF. MODBUS DATA BESCHIKBAAR.", /* CLText_DATA_AVAILABLE_FROM_MODBUS */
	"KANAAL", /* CLText_RFM__CHANNEL */
	"STATUS", /* CLText_RFM__STATUS */
	"KIES RFM KANAAL ", /* CLText_RFM__CHANGE_CHANNEL */
	"VERBINDEN", /* CLText_CONNECTING */
	"VRIJ", /* CLText_RFM__CHANNEL_FREE */
	"BEZET", /* CLText_RFM__CHANNEL_BUSY */
	"IN UITVOERING", /* CLText_RFM__CHANNEL_INPROGRESS */
	"RFM KANAAL IS BEZET. VERANDER KANAAL A.U.B.", /* CLText_RFM__ALERT_CHANNEL_BUSY */
	"DRUK OK OM OPNIEUW VERBINDING TE MAKEN.", /* CLText_CONNECT__RETRY_CONNECTION_MESSAGE */
	"BEZIG RFM KANAAL TE CONTROLEREN", /* CLText_RFM__CHECKING_CHANNEL_IN_PROGRESS */
	"BRANDALARM", /* CLText_FIREALARM_FIRE_ALARM */
	"REFERENTIE T. INSTELLINGEN", /* CLText_REFERENCE_T_SETTING */
	"SEC.", /* CLText_SECOND_ABBR */
	"REFERENTIE SONDE", /* CLText_DXDSETTINGS_REFERENCEPROBE */
	"DELTA TEMPERATUUR", /* CLText_DXDSETTINGS_DELTATEMPERATURE */
	"VERTRAGING", /* CLText_DXDSETTINGS_DELAY */
	"BYPASS WORDT GESTUURD DOOR EEN EXTERNE INGANG", /* CLText_BYPASS_OPERATED_BY_EXT_INPUT */
	"CAP CALIBRATIE PROCEDURE", /* CLText_CAP_CALIBRATION_PROCEDURE */
	"ALLE KLEPPEN IN SYSTEEM OPENEN EN DRUK OP OK INDIEN GEREED", /* CLText_CAP_CALIBRATION_START_MESSAGE */
	"CALIBRATIE BEZIG.\rEEN MOMENT GEDULD A.U.B. ...", /* CLText_CAP_CALIBRATION_RUNNING_MESSAGE */
	"GEDETECTEERDE DRUK BEVESTIGEN?", /* CLText_CAP_CALIBRATION_CONFIRMDATA_MESSAGE */
	"AUTOMATISCH (AAN + STANDBY)", /* CLText_AUTOMATIC_ON_STANDBY */
	"BRANDALARM GEACTIVEERD", /* CLText_FIREALARM_ALARM_ACTIVATED */
	"BRANDALARM UITGESCHAKELD", /* CLText_FIREALARM_ALARM_DEACTIVATED */
	"CONFIGURATIE", /* CLText_FIREALARM_CONFIGURATION */
	"DRUK OP DE RESETKNOP VOOR EEN HERSTART VAN DE NORMALE WERKING VAN HET APPARAAT", /* CLText_FIREALARM_REARM_MESSAGE */
	"RESET", /* CLText_FIREALARM_REARM */
	"PARTY", /* CLText_PARTY_MODE */
	CLText_NoText, /* PROCEDURE_STARTING_MESSAGE */
	CLText_NoText, /* PROCEDURE_RUNNING_MESSAGE */
	CLText_NoText, /* PROCEDURE_COMPLETED_MESSAGE */
	CLText_NoText, /* DPP_THRESHOLD */
	CLText_NoText, /* DPP_CALIBRATION */
	CLText_NoText, /* DPP_FILTER_LEVEL */
	"ALLE ACC. UITSCHAKELEN", /* Disconnect all accessories */
};

