#include "CLLanguage_SL.h"

const char* gLanguage_SLTexts[ CLTextId__TEXT_COUNT ] =
{
	"BYPASS ",   /* BYPASS */
	"ODTALJEVANJE",   /* DEFROST */
	"FILTRI",   /* FILTERS */
	"MENI",   /* MENU */
	"SHRANI",   /* SAVE */
	"CAS",   /* TIME */
	"DATUM",   /* DATE */
	"IZBERI KTS",   /* SELECT_KTS */
	"NASTAVI BOX INFO",   /* CONFIG_BOX_INFO */
	"JEZIKOVNE NASTAVITVE",   /* SELECTION_LANGUAGE */
	"NASTAVITVE OHRANJEVALNIKA ZASLONA",   /* CONFIG_SCREEN_SAVER */
	"NADGRADNJA",   /* UPGRADE */
	"NASTAVITEV DATUMA",   /* DATE_SETTINGS */
	"NASTAVITEV TREH HITROSTI",   /* THREE_SPEED_SETTINGS */
	"TEDENSKO PROGRAMIRANJE",   /* WEEKLY_PROGRAMMER */
	"TUCH KALIBRACIJA DOTIKA",   /* TOUCH_CALIBRATION */
	"NASTAVITVE FILTRA",   /* FILTER_SETTINGS */
	"NASTAVITVE BYPASS-A",   /* BPD_SETTINGS */
	"NEURAVNOTEZEN PRETOK ZRAKA",   /* UNBALANCE_AIRFLOW */
	"NADGRADNJA AKTIVACIJE",   /* UPGRADE_ACTIVATION */
	"NAPACNO GESLO",   /* PASSWORD_INCORRECT */
	"SERIJSKA ID STEVILKA",   /* SERIAL_ID */
	"FIRMWARE VERZIJA",   /* FIRMWARE_VERSION */
	"TIP ENOTE",   /* UNIT_TYPE */
	"DODATKI - OPREMA",   /* ACCESSORY */
	"NASTAVITVE",   /* SETTINGS */
	"SERVIS",   /* SERVICE */
	"INFORMACIJE",   /* INFO */
	"IZBIRA JEZIKA",   /* SELECT_LANGUAGE */
	"P",   /* MONDAY_SHORTNAME */
	"T",   /* TUESDAY_SHORTNAME */
	"S",   /* WEBNESDAY_SHORTNAME */
	"C",   /* THURSDAY_SHORTNAME */
	"P",   /* FRIDAY_SHORTNAME */
	"S",   /* SATURDAY_SHORTNAME */
	"N",   /* SUNDAY_SHORTNAME */
	"PRILEPI",   /* PASTE */
	"KOPIRAJ",   /* COPY */
	"NASTAVI PRVO PODROCJE ",   /* SET_FIRST_RANGE */
	"NASTAVI DRUGO PODROCJE",   /* SET_SECOND_RANGE */
	"NASTAVI TRETJE PODROCJE",   /* SET_THIRD_RANGE */
	"NASTAVI CETRTO PODROCJE",   /* SET_FOURTH_RANGE */
	"ZACETNI CAS",   /* START_TIME */
	"KONCNI CAS",   /* END_TIME */
	"PRETOK ZRAKA",   /* AIR_FLOW */
	"PONEDELJEK",   /* MONDAY */
	"TOREK",   /* TUESDAY */
	"SREDA",   /* WEDNESDAY */
	"CETRTEK",   /* THURSDAY */
	"PETEK",   /* FRIDAY */
	"SOBOTA",   /* SATURDAY */
	"NEDELJA",   /* SUNDAY */
	"UPORABITE KODO",   /* MAKE_USE_OF_A_STYLUS_PEN */
	"PRITISNI MODRI GUMB",   /* PRESS_THE_BLUE_BAR */
	"NASTAVITEV HITROSTI",   /* SELECT_SPEED_MODE */
	"3 HITROSTI",   /* THREE_SPEED */
	"ZVEZNO",   /* STEPLESS */
	"IZBERI MINIMALNO HITROST",   /* SELECT_SPEED_MIN */
	"IZBERI SREDNJO HITROST",   /* SELECT_SPEED_MED */
	"IZBERI MAKSIMALNO HITROST",   /* SELECT_SPEED_MAX */
	"NASTAVI CAS MENJAVE FILTRA",   /* SET_FILTER_TIME */
	"MESECI",   /* MONTHS */
	"NASTAVI NEURAVNOTEZENOST",   /* SET_UNBALANCE */
	"NAZAJ",   /* BACK */
	"ACCESSORY MANAGER",   /* ACCESSORY_MANAGER */
	"NASTAVITVE KLIME",   /* CLIMA_SETTINGS */
	"NASTAVITEV TEMPERATUR",   /* TEMPERATURE_SETTINGS */
	"TEDENSKE NASTAVITVE",   /* WEEKLY_SETTINGS */
	"PROGRAM",   /* PROGRAM */
	"POGLED",   /* VIEW */
	"PROG ",   /* PROG */
	"NASTAVI STEVILO PODROCJI - INTERVALOV ",   /* SET_NBR_OF_RANGES */
	"VRNITEV",   /* RETURN */
	"NAPRAVA",   /* UNIT */
	"ISKANJE",   /* SEARCHING */
	"NAPAKA",   /* ERROR */
	"NE NAJDE NAPRAVE",   /* UNIT_NOT_FOUND */
	"PROSIM PREVERITE",   /* PLEASE_CHECK_THE */
	"KABEL IN PONOVNO ZAZENITE",   /* CABLE_AND_RESTART */
	"SISTEM",   /* THE_SYSTEM */
	"POVEZAN",   /* CONNECTED */
	"ONEMOGOCENO",   /* DISABLE */
	"TUCH KALIBRACIJA DOTIKA",   /* TOUCH_CALIBRATED */
	"OPOZORILA:",   /* WARNINGS_REPORT */
	"ZAHTEVA ZA MENJAVO FILTRA",   /* RECOMMEND_TO_CHANGE_FILTERS */
	"PRAVILNO GESLO",   /* PASSWORD_CORRECT */
	"NED ",   /* SUN */
	"PON ",   /* MON */
	"TOR ",   /* TUE */
	"SRE ",   /* WED */
	"CET ",   /* THU */
	"PET ",   /* FRI */
	"SOB ",   /* SAT */
	"NC",   /* NC */
	"RH NASTAVITVE VLAGE",   /* RH_SETTINGS */
	"NASTAVITEV PRAGA RH",   /* SET_RH_THRESHOLD */
	"CO2 NASTAVITVE KVALITETE ZRAKA",   /* CO2_SETTINGS */
	"      CO2             PRETOK ZRAKA",   /* SET_CO2_THRESHOLD */
	"STEVEC",   /* COUNTER */
	"NASTAVITVE \"PARTY\"",   /* PARTY_SETTINGS */
	"NASTAVI \"PARTY\" CAS",   /* SET_PARTY_TIMER */
	"DOGODEK",   /* EVENT */
	"TEDEN",   /* WEEK */
	"TIPALA",   /* PROBES */
	"KONFIGURACIJA",   /* CONFIG */
	"NASTAVITVE TEMP. KRIVULJE",   /* HYSTER_TEMPSET */
	"POLETJE",   /* SUMMER */
	"ZIMA",   /* WINTER */
	"T.SVEZI",   /* TFRESH */
	"TEMPERATURNE KRIVULJE",   /* TEMPERATURE_HYSTERESIS */
	"DOVOD",   /* SUPPLY */
	"ODVOD",   /* EXTRACT */
	"POROCILO",   /* REPORT_DATA */
	"SENZOR TLAKA ",   /* PRESSURE_SENSOR */
	"RAVEN SIGNALA (LINK SENZOR)",   /* LEVEL_LINK_SENSOR */
	"NASTAVLJEN TLAK",   /* SETPOINT_PRESSURE */
	"IZMERJEN TLAK",   /* MEASURE_PRESSURE */
	"HITROST MOTORJA",   /* SPEED_MOTORS */
	"POVEZAN",   /* CONNECT */
	"NI POVEZAVE",   /* NOT_CONNECTED */
	"ODSTRANI  OPREMO",   /* REMOVE_ACCESSORY */
	"POTRJUJES ODSTRANITEV?",   /* CONFIRM_REMOVE */
	"T.POVRATKA",   /* TRETURN */
	"DA",   /* YES */
	"NE",   /* NO */
	"ROCNO",   /* MANUAL */
	"AVTOMATSKO",   /* AUTOMATIC */
	"ODPRT",   /* OPEN */
	"ZAPRT",   /* CLOSED */
	"KLIMATIZACIJA",   /* CLIMA */
	"GESLO",   /* PASSWORD */
	"VROCE",   /* HOT */
	"MRZLO",   /* COLD */
	"PONASTAVITEV - RESET",   /* RESET */
	"NASTAVITVE  VNOSA \"INPUT\"",   /* INPUT_CONFIG */
	"0V = STOP",   /* INPUT_CONFIG_0V_STOP */
	"10V = STOP",   /* INPUT_CONFIG_10V_STOP */
	"0V = ODPRTO",   /* INPUT_CONFIG_0V_OPEN */
	"10V = ODPRTO",   /* INPUT_CONFIG_10V_OPEN */
	"REGULACIJA PRETOKA ZRAKA",   /* INPUT_CONFIG_REG_AIR_FLOW */
	"NASTAVITVE IZHODOV \"OUTPUT\"",   /* OUTPUT_CONFIG */
	"IZBERI RAVEN - KLASO TX",   /* SELECT_FRANCE_CLASSTX */
	"RAVEN - KLASA TX",   /* FRANCE_CLASSTX */
	"KONTROLA PREZRACEVANJA",   /* VENTILATION_CONTROL */
	"VOC NASTAVITVE ",   /* VOC_CONFIG */
	"TEMPERATURA",   /* TEMPERATURE */
	"HITROST  ",   /* SPEED */
	"KONTROLA KLIMATIZACIJE",   /* CLIMA_CONTROL */
	"IZPIS PODATKOV V TEKU",   /* WRITING_DATA */
	"IZPIS PODATKOV ZAKLJUCEN",   /* WRITING_DATA_COMPLETED */
	"NAPAKA PRI IZPISU PODATKOV",   /* WRITING_DATA_ERROR */
	"V ALARMU",   /* IN_ALARM */
	"ZUNANJE UPRAVLJANJE",   /* EXTERNAL_CONTROL */
	"LISTA NAPAK (ERRORS LIST)",   /* ERRORS_REPORT */
	"NASTAVI OBMOCJE",   /* SET_RANGE */
	"ROCNI IZKLOP (OFF)",   /* MANUAL_OFF */
	"ROCNI VKLOP (ON)",   /* MANUAL_ON */
	"ROCNO ZAPRTO",   /* MANUAL_CLOSE */
	"ROCNO ODPRTO",   /* MANUAL_OPEN */
	"AVTOMATSKI IZKLOP",   /* AUT_OFF */
	"AVTOMATSKI VKLOP",   /* AUT_ON */
	"SPREMINJANJE",   /* CHANGING */
	"MINIMALNO",   /* MINUTE_ABBR */
	"NASTAVITVE PRETOKA ZRAKA",   /* AIRFLOW_CONFIG */
	"CK VODE",   /* WATER_CK */
	"IZBERI DOGODEK",   /* SELECT_EVENT */
	"BYPASS ODPRT",   /* BYPASS_OPEN */
	"BYPASS ZAPRT",   /* BYPASS_CLOSE */
	"NAPRAVA DELUJE",   /* UNIT_RUN */
	"NAPRAVA NE DELUJE",   /* UNIT_FAULT */
	"IZBERI AKCIJO",   /* SELECT_ACTION */
	"STARO GESLO",   /* OLD_PASSWORD */
	"NOVO GESLO",   /* NEW_PASSWORD */
	"PONOVI NOVO GESLO",   /* REPEAT_NEW_PASSWORD */
	"SPREMENI UPORABNISKO GESLO ",   /* CHANGE_END_USER_PASSWORD */
	"SPREMENI SERVISNO GESLO",   /* CHANGE_SERVICE_PASSWORD */
	"SPREMENI GESLO",   /* CHANGE_PASSWORD */
	"NASTAVITVE GESLA",   /* PASSWORD_SETTINGS */
	"SPREMEMBA PODATKOV",   /* DATA_CHANGED */
	"SHRANIM  SPREMEMBE?",   /* SAVE_CHANGES */
	"RAZVELJAVI",   /* CANCEL */
	"NASTAVITVE TIPAL",   /* PROBES_SETTINGS */
	"GRELNIK",   /* HEATER */
	"HLADILNIK",   /* COOLER */
	"DNEVI",   /* DAYS */
	"ODKLOPLJEN ACC.",   /* DISCONNECT_ACCESSORY */
	"ACC. KLIMA",   /* BOXINFO_ACCESSORY_CLIMA */
	"HARDWARE VERZIJA MB",   /* MB_HARDWARE_VERSION */
	"SOFTWARE VERZIJA MB",   /* MB_SOFTWARE_VERSION */
	"PREDGRELEC",   /* PREHEATER */
	"DOGRELEC",   /* POSTHEATER */
	"NOTRANJE",   /* INTERNAL */
	"PRETOK ZRAKA",   /* MEASURE_AIRFLOW */
	"NASTAVITVE \"MODBUS\"",   /* MODBUS_SETTINGS */
	"NASLOVI",   /* MODBUS_ADDRESS */
	"STATUSI",   /* MODBUS_STATUS */
	"ODKLOPLJEN",   /* DISCONNECTED */
	"MIN.ZUNANJA TEMPERATURA",   /* BYPASS_MIN_EXT_TEMPERATURE */
	"MODBUS AKTIVEN. MODBUS RAZPOLOZLJIVI PODATKI",   /* DATA_AVAILABLE_FROM_MODBUS */
	"KANAL",   /* RFM__CHANNEL */
	"STATUSI",   /* RFM__STATUS */
	"NASTAVI \"RFM\" KANAL",   /* RFM__CHANGE_CHANNEL */
	"POVEZOVANJE",   /* CONNECTING */
	"PROST",   /* RFM__CHANNEL_FREE */
	"ZASEDEN",   /* RFM__CHANNEL_BUSY */
	"V TEKU",   /* RFM__CHANNEL_INPROGRESS */
	"RMF KANAL JE ZASEDEN. ZAMENJAJ PROSIM.",   /* RFM__ALERT_CHANNEL_BUSY */
	"PRITISNI OK ZA PONOVNI POIZKUS POVEZAVE.",   /* CONNECT__RETRY_CONNECTION_MESSAGE */
	"PREVERJANJE RFM KANALA V TEKU.",   /* RFM__CHECKING_CHANNEL_IN_PROGRESS */
	CLText_NoText,   /* FIREALARM_FIRE_ALARM */
	"REFERENCNA T NASTAVITEV",   /* REFERENCE_T_SETTING */
	"SEK.",   /* SECOND_ABBR */
	"REFERENCNO TIPALO",   /* DXDSETTINGS_REFERENCEPROBE */
	"ODSTOPANJE TEMPERATURE",   /* DXDSETTINGS_DELTATEMPERATURE */
	"ZAKASNITEV",   /* DXDSETTINGS_DELAY */
	CLText_NoText,   /* BYPASS_OPERATED_BY_EXT_INPUT */
	CLText_NoText,   /* CAP_CALIBRATION_PROCEDURE */
	CLText_NoText,   /* CAP_CALIBRATION_START_MESSAGE */
	CLText_NoText,   /* CAP_CALIBRATION_RUNNING_MESSAGE */
	CLText_NoText,   /* CAP_CALIBRATION_CONFIRMDATA_MESSAGE */
	CLText_NoText,   /* AUTOMATIC_ON_STANDBY */
	CLText_NoText,   /* FIREALARM_ALARM_ACTIVATED */
	CLText_NoText,   /* FIREALARM_ALARM_DEACTIVATED */
	CLText_NoText,   /* FIREALARM_CONFIGURATION */
	CLText_NoText,   /* FIREALARM_REARM_MESSAGE */
	CLText_NoText,   /* FIREALARM_REARM */
	CLText_NoText,   /* PARTY_MODE */
	CLText_NoText, /* PROCEDURE_STARTING_MESSAGE */
	CLText_NoText, /* PROCEDURE_RUNNING_MESSAGE */
	CLText_NoText, /* PROCEDURE_COMPLETED_MESSAGE */
	CLText_NoText, /* DPP_THRESHOLD */
	CLText_NoText, /* DPP_CALIBRATION */
	CLText_NoText, /* DPP_FILTER_LEVEL */
	CLText_NoText, /* Disconnect all accessories */
};

