#include "CLLanguage_TR.h"

const char* gLanguage_TRTexts[ CLTextId__TEXT_COUNT ] =
{
	"BYPASS",   /* BYPASS */
	"DEFROST",   /* DEFROST */
	"FILTERS",   /* FILTERS */
	"MENU",   /* MENU */
	"SAVE",   /* SAVE */
	"TIME",   /* TIME */
	"DATE:",   /* DATE */
	"SELECT KTS",   /* SELECT_KTS */
	"SET BOX INFO",   /* CONFIG_BOX_INFO */
	"LANGUAGE SETTINGS",   /* SELECTION_LANGUAGE */
	"SCREENSAVER SETTINGS",   /* CONFIG_SCREEN_SAVER */
	"UPGRADE",   /* UPGRADE */
	"DATE SETTINGS",   /* DATE_SETTINGS */
	"THREE SPEED SETTINGS",   /* THREE_SPEED_SETTINGS */
	"WEEKLY PROGRAMMER",   /* WEEKLY_PROGRAMMER */
	"TOUCH CALIBRATION",   /* TOUCH_CALIBRATION */
	"FILTER SETTINGS",   /* FILTER_SETTINGS */
	"BPD SETTINGS",   /* BPD_SETTINGS */
	"UNBALANCE AIRFLOW",   /* UNBALANCE_AIRFLOW */
	"UPGRADE ACTIVATION",   /* UPGRADE_ACTIVATION */
	"PASSWORD INCORRECT",   /* PASSWORD_INCORRECT */
	"SERIAL ID",   /* SERIAL_ID */
	"FIRMWARE VERSION",   /* FIRMWARE_VERSION */
	"UNIT TYPE",   /* UNIT_TYPE */
	"ACCESSORY",   /* ACCESSORY */
	"SETTINGS",   /* SETTINGS */
	"SERVICE",   /* SERVICE */
	"INFO",   /* INFO */
	"SELECT LANGUAGE",   /* SELECT_LANGUAGE */
	"M",   /* MONDAY_SHORTNAME */
	"T",   /* TUESDAY_SHORTNAME */
	"W",   /* WEBNESDAY_SHORTNAME */
	"T",   /* THURSDAY_SHORTNAME */
	"F",   /* FRIDAY_SHORTNAME */
	"S",   /* SATURDAY_SHORTNAME */
	"S",   /* SUNDAY_SHORTNAME */
	"PASTE",   /* PASTE */
	"COPY",   /* COPY */
	"SET FIRST RANGE",   /* SET_FIRST_RANGE */
	"SET SECOND RANGE",   /* SET_SECOND_RANGE */
	"SET THIRD RANGE",   /* SET_THIRD_RANGE */
	"SET FOURTH RANGE",   /* SET_FOURTH_RANGE */
	"START TIME",   /* START_TIME */
	"END TIME",   /* END_TIME */
	"AIR FLOW",   /* AIR_FLOW */
	"MONDAY",   /* MONDAY */
	"TUESDAY",   /* TUESDAY */
	"WEDNESDAY",   /* WEDNESDAY */
	"THURSDAY",   /* THURSDAY */
	"FRIDAY",   /* FRIDAY */
	"SATURDAY",   /* SATURDAY */
	"SUNDAY",   /* SUNDAY */
	"MAKE USE OF A STYLUS PEN",   /* MAKE_USE_OF_A_STYLUS_PEN */
	"PRESS THE BLUE BAR",   /* PRESS_THE_BLUE_BAR */
	"SELECT SPEED MODE",   /* SELECT_SPEED_MODE */
	"THREE SPEED",   /* THREE_SPEED */
	"STEPLESS",   /* STEPLESS */
	"SELECT SPEED MIN",   /* SELECT_SPEED_MIN */
	"SELECT SPEED MED",   /* SELECT_SPEED_MED */
	"SELECT SPEED MAX",   /* SELECT_SPEED_MAX */
	"SET FILTER TIME",   /* SET_FILTER_TIME */
	"MONTHS",   /* MONTHS */
	"SET UNBALANCE",   /* SET_UNBALANCE */
	"BACK",   /* BACK */
	"ACCESSORY MANAGER",   /* ACCESSORY_MANAGER */
	"CLIMA SETTINGS",   /* CLIMA_SETTINGS */
	"TEMPER. SETTINGS",   /* TEMPERATURE_SETTINGS */
	"WEEKLY SETTINGS",   /* WEEKLY_SETTINGS */
	"PROGRAM",   /* PROGRAM */
	"VIEW",   /* VIEW */
	"PROG",   /* PROG */
	"SET NR OF RANGES:",   /* SET_NBR_OF_RANGES */
	"RETURN",   /* RETURN */
	"UNIT",   /* UNIT */
	"SEARCHING...",   /* SEARCHING */
	"ERROR",   /* ERROR */
	"UNIT NOT FOUND",   /* UNIT_NOT_FOUND */
	"PLEASE CHECK THE",   /* PLEASE_CHECK_THE */
	"CABLE AND RESTART",   /* CABLE_AND_RESTART */
	"THE SYSTEM",   /* THE_SYSTEM */
	"CONNECTED",   /* CONNECTED */
	"DISABLE",   /* DISABLE */
	"TOUCH CALIBRATED",   /* TOUCH_CALIBRATED */
	"WARNING REPORTS:",   /* WARNINGS_REPORT */
	"RECOMMEND TO CHANGE FILTERS",   /* RECOMMEND_TO_CHANGE_FILTERS */
	"PASSWORD CORRECT",   /* PASSWORD_CORRECT */
	"SUN",   /* SUN */
	"MON",   /* MON */
	"TUE",   /* TUE */
	"WED",   /* WED */
	"THU",   /* THU */
	"FRI",   /* FRI */
	"SAT",   /* SAT */
	"NC",   /* NC */
	"RH SETTINGS",   /* RH_SETTINGS */
	"SET RH THRESHOLD",   /* SET_RH_THRESHOLD */
	"CO2 SETTINGS",   /* CO2_SETTINGS */
	"SET CO2 THRESHOLD:",   /* SET_CO2_THRESHOLD */
	"COUNTER",   /* COUNTER */
	"PARTY SETTINGS",   /* PARTY_SETTINGS */
	"SET PARTY TIMER:",   /* SET_PARTY_TIMER */
	"EVENT",   /* EVENT */
	"WEEK",   /* WEEK */
	"PROBES",   /* PROBES */
	"CONFIG",   /* CONFIG */
	"HYSTER. TEMP.SET.",   /* HYSTER_TEMPSET */
	"SUMMER",   /* SUMMER */
	"WINTER",   /* WINTER */
	"T.FRESH",   /* TFRESH */
	"TEMPER. HYSTERESIS",   /* TEMPERATURE_HYSTERESIS */
	"SUPPLY",   /* SUPPLY */
	"EXTRACT",   /* EXTRACT */
	"REPORT DATA",   /* REPORT_DATA */
	"PRESSURE SENSOR:",   /* PRESSURE_SENSOR */
	"LEVEL LINK SENSOR:",   /* LEVEL_LINK_SENSOR */
	"SETPOINT PRESSURE:",   /* SETPOINT_PRESSURE */
	"MEASURE PRESSURE:",   /* MEASURE_PRESSURE */
	"SPEED MOTORS:",   /* SPEED_MOTORS */
	"CONNECT",   /* CONNECT */
	"NOT CONNECTED",   /* NOT_CONNECTED */
	"REMOVE ACCESSORY",   /* REMOVE_ACCESSORY */
	"CONFIRM REMOVAL?",   /* CONFIRM_REMOVE */
	"T. RETURN",   /* TRETURN */
	"YES",   /* YES */
	"NO",   /* NO */
	"MANUAL",   /* MANUAL */
	"AUTOMATIC (ON)",   /* AUTOMATIC_ON */
	"OPEN",   /* OPEN */
	"CLOSED",   /* CLOSED */
	"CLIMA",   /* CLIMA */
	"PASSWORD",   /* PASSWORD */
	"HOT",   /* HOT */
	"COLD",   /* COLD */
	"RESET",   /* RESET */
	"INPUT SETTINGS",   /* INPUT_CONFIG */
	"0V = STOP",   /* INPUT_CONFIG_0V_STOP */
	"10V = STOP",   /* INPUT_CONFIG_10V_STOP */
	"0V = OPEN",   /* INPUT_CONFIG_0V_OPEN */
	"10V = OPEN",   /* INPUT_CONFIG_10V_OPEN */
	"REG AIR FLOW",   /* INPUT_CONFIG_REG_AIR_FLOW */
	"OUTPUT SETTINGS",   /* OUTPUT_CONFIG */
	"SELECT CLASS TX",   /* SELECT_FRANCE_CLASSTX */
	"CLASS TX",   /* FRANCE_CLASSTX */
	"VENTILATION CONTROL",   /* VENTILATION_CONTROL */
	"VOC SETTTINGS",   /* VOC_CONFIG */
	"TEMPERATURES",   /* TEMPERATURE */
	"SPEED",   /* SPEED */
	"CLIMA CONTROL",   /* CLIMA_CONTROL */
	"WRITING DATA IN PROGRESS...",   /* WRITING_DATA */
	"WRITING DATA COMPLETED",   /* WRITING_DATA_COMPLETED */
	"ERROR WHILE WRITING DATA",   /* WRITING_DATA_ERROR */
	"IN ALARM",   /* IN_ALARM */
	"EXTERNAL CONTROL",   /* EXTERNAL_CONTROL */
	"ERRORS LIST",   /* ERRORS_REPORT */
	"SET RANGE",   /* SET_RANGE */
	"MAN. OFF",   /* MANUAL_OFF */
	"MAN. ON",   /* MANUAL_ON */
	"MAN. CLOSED",   /* MANUAL_CLOSE */
	"MAN. OPEN",   /* MANUAL_OPEN */
	"AUT. OFF",   /* AUT_OFF */
	"AUT. ON",   /* AUT_ON */
	"CHANGING",   /* CHANGING */
	"MIN.",   /* MINUTE_ABBR */
	"AIR FLOW SETTINGS",   /* AIRFLOW_CONFIG */
	"WATER CK",   /* WATER_CK */
	"SELECT EVENT",   /* SELECT_EVENT */
	"BYPASS OPEN",   /* BYPASS_OPEN */
	"BYPASS CLOSED",   /* BYPASS_CLOSE */
	"UNIT RUN",   /* UNIT_RUN */
	"UNIT FAULT",   /* UNIT_FAULT */
	"SELECT ACTION",   /* SELECT_ACTION */
	"OLD PASSWORD",   /* OLD_PASSWORD */
	"NEW PASSWORD",   /* NEW_PASSWORD */
	"REPEAT NEW PASSWORD",   /* REPEAT_NEW_PASSWORD */
	"CHANGE USER PWD",   /* CHANGE_END_USER_PASSWORD */
	"CHANGE SERVICE PWD",   /* CHANGE_SERVICE_PASSWORD */
	"CHANGE PASSWORD",   /* CHANGE_PASSWORD */
	"PASSWORD SETTINGS",   /* PASSWORD_SETTINGS */
	"DATA CHANGED",   /* DATA_CHANGED */
	"SAVE CHANGES?",   /* SAVE_CHANGES */
	"CANCEL",   /* CANCEL */
	"PROBES SETTINGS",   /* PROBES_SETTINGS */
	"HEATER",   /* HEATER */
	"COOLER",   /* COOLER */
	"DAYS",   /* DAYS */
	"DISCONNECT ACC.",   /* DISCONNECT_ACCESSORY */
	"ACC. CLIMA",   /* BOXINFO_ACCESSORY_CLIMA */
	"HARDWARE VERSION MB",   /* MB_HARDWARE_VERSION */
	"SOFTWARE VERSION MB",   /* MB_SOFTWARE_VERSION */
	"PRE HEATER",   /* PREHEATER */
	"POST HEATER",   /* POSTHEATER */
	"INTERNAL",   /* INTERNAL */
	"AIRFLOW",   /* MEASURE_AIRFLOW */
	"MODBUS SETTINGS",   /* MODBUS_SETTINGS */
	"ADDRESS",   /* MODBUS_ADDRESS */
	"STATUS",   /* MODBUS_STATUS */
	"DISCONNECTED",   /* DISCONNECTED */
	"EXT. TEMP. MIN.",   /* BYPASS_MIN_EXT_TEMPERATURE */
	"MODBUS ACTIVE. DATA AVAILABLE FROM MODBUS.",   /* DATA_AVAILABLE_FROM_MODBUS */
	"CHANNEL",   /* RFM__CHANNEL */
	"STATUS",   /* RFM__STATUS */
	"SET RFM CHANNEL",   /* RFM__CHANGE_CHANNEL */
	"CONNECTING",   /* CONNECTING */
	"FREE",   /* RFM__CHANNEL_FREE */
	"BUSY",   /* RFM__CHANNEL_BUSY */
	"IN PROGRESS",   /* RFM__CHANNEL_INPROGRESS */
	"RFM CHANNEL IS BUSY. PLEASE CHANGE.",   /* RFM__ALERT_CHANNEL_BUSY */
	"PRESS OK TO RETRY CONNECTION.",   /* CONNECT__RETRY_CONNECTION_MESSAGE */
	"CHECKING RFM CHANNEL IN PROGRESS",   /* RFM__CHECKING_CHANNEL_IN_PROGRESS */
	"FIRE ALARM",   /* FIREALARM_FIRE_ALARM */
	"REFERENCE T. SETTINGS",   /* REFERENCE_T_SETTING */
	"SEC.",   /* SECOND_ABBR */
	"REFERENCE PROBE",   /* DXDSETTINGS_REFERENCEPROBE */
	"DELTA TEMPERATURE",   /* DXDSETTINGS_DELTATEMPERATURE */
	"DELAY",   /* DXDSETTINGS_DELAY */
	"BYPASS IS OPERATED BY AN EXTERNAL INPUT",   /* BYPASS_OPERATED_BY_EXT_INPUT */
	"CAP CALIBRATION PROCEDURE",   /* CAP_CALIBRATION_PROCEDURE */
	"OPEN ALL THE VALVES IN YOUR SYSTEM AND PRESS OK WHEN READY",   /* CAP_CALIBRATION_START_MESSAGE */
	"CALIBRATION IN PROGRESS\nPLEASE WAIT",   /* CAP_CALIBRATION_RUNNING_MESSAGE */
	"CONFIRM DETECTED PRESSURE?",   /* CAP_CALIBRATION_CONFIRMDATA_MESSAGE */
	"AUTOMATIC (ON + STANDBY)",   /* AUTOMATIC_ON_STANDBY */
	"FIRE ALARM ENABLED",   /* FIREALARM_ALARM_ACTIVATED */
	"FIRE ALARM DISABLED",   /* FIREALARM_ALARM_DEACTIVATED */
	"CONFIGURATION",   /* FIREALARM_CONFIGURATION */
	"TO RESTART THE NORMAL OPERATION OF THE MACHINE MUST PRESS THE RESET BUTTON",   /* FIREALARM_REARM_MESSAGE */
	"RESET",   /* FIREALARM_REARM */
	"PARTY",   /* PARTY_MODE */
};

